package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.InsuranceStatus;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.InsuranceStatus_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/InsuranceStatus_Activity", description = "InsuranceStatus_Activity of InsuranceStatus_Activity",produces = "application/json")
@CrossOrigin
@Controller("InsuranceStatus_ActivityController")
@RequestMapping("/api/InsuranceStatus_Activity")
public class InsuranceStatus_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(InsuranceStatus_ActivityController.class.getName());

 


	private InsuranceStatus_ActivityService InsuranceStatus_Activity_service;


	public InsuranceStatus_ActivityService get_InsuranceStatus_Activity_service() {
		return InsuranceStatus_Activity_service;
	}


	@Resource(name="InsuranceStatus_ActivityService")
	public void set_InsuranceStatus_Activity_service(InsuranceStatus_ActivityService InsuranceStatus_Activity_service) {
		this.InsuranceStatus_Activity_service = InsuranceStatus_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  InsuranceStatus noun into database
	* @param the_InsuranceStatus
	*@return InsuranceStatus object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_InsuranceStatus", httpMethod = "POST",notes = "creates a noun of InsuranceStatus",response = InsuranceStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_InsuranceStatus" ,headers="Accept=application/json")
    @ResponseBody
	public InsuranceStatus create_InsuranceStatus(@RequestBody InsuranceStatus the_InsuranceStatus) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_InsuranceStatus controller started operation!");

		the_InsuranceStatus.setId(null);

		InsuranceStatus a_InsuranceStatus = InsuranceStatus_Activity_service.create_insurancestatus(the_InsuranceStatus);

		log.info("Object returned from create_InsuranceStatus method !");

 

        return a_InsuranceStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  InsuranceStatus noun into database
	*@param the_InsuranceStatus
	*@return InsuranceStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_InsuranceStatus", httpMethod = "PUT",notes = "updates a noun of InsuranceStatus",response = InsuranceStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_InsuranceStatus" ,headers="Accept=application/json")
    @ResponseBody
	public InsuranceStatus update_InsuranceStatus(@RequestBody InsuranceStatus the_InsuranceStatus) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_InsuranceStatus controller started operation!");

		InsuranceStatus a_InsuranceStatus;

		a_InsuranceStatus = InsuranceStatus_Activity_service.update_insurancestatus(the_InsuranceStatus);

		log.info("Object returned from update_InsuranceStatus method !");

 

        return a_InsuranceStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  InsuranceStatus noun from  database based on given noun id
	*@param InsuranceStatus_id
	*@return InsuranceStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_InsuranceStatus/{InsuranceStatus_id}", httpMethod = "GET",notes = "updates a noun of InsuranceStatus",response = InsuranceStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_InsuranceStatus/{InsuranceStatus_id}" ,headers="Accept=application/json")
    @ResponseBody
	public InsuranceStatus search_for_update_InsuranceStatus(@PathVariable("InsuranceStatus_id")String InsuranceStatus_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_InsuranceStatus controller started operation!");

		InsuranceStatus the_InsuranceStatus = new InsuranceStatus();

		the_InsuranceStatus = InsuranceStatus_Activity_service.insurancestatus_search_for_update(InsuranceStatus_id);

		log.info("Object returned from search_for_update_InsuranceStatus method !");

 

        return the_InsuranceStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  InsuranceStatus noun from  database based on given noun id
	*@param InsuranceStatus_id
	*@return InsuranceStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_InsuranceStatus/{InsuranceStatus_id}", httpMethod = "DELETE",notes = "deletes a noun of InsuranceStatus",response = InsuranceStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_InsuranceStatus/{InsuranceStatus_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_InsuranceStatus(@PathVariable("InsuranceStatus_id")String  InsuranceStatus_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_InsuranceStatus controller started operation!");

		String service_return_msg = "";

		service_return_msg = InsuranceStatus_Activity_service.delete_insurancestatus(InsuranceStatus_id);

		log.info("Object returned from delete_InsuranceStatus method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  InsuranceStatus noun from  database
	*
	*@return List of InsuranceStatus objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_InsuranceStatus", httpMethod = "GET",notes = "special search that gets all values of InsuranceStatus",response = InsuranceStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_InsuranceStatus" ,headers="Accept=application/json")
    @ResponseBody
	public List<InsuranceStatus> get_all_InsuranceStatus() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_InsuranceStatus controller started operation!");

		List<InsuranceStatus> InsuranceStatus_list = new ArrayList<InsuranceStatus>();

		InsuranceStatus_list = InsuranceStatus_Activity_service.get_all_insurancestatus();

		log.info("Object returned from get_all_InsuranceStatus method !");

 

        return InsuranceStatus_list;

	}




}