package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.Poyear;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.Poyear_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/Poyear_Activity", description = "Poyear_Activity of Poyear_Activity",produces = "application/json")
@CrossOrigin
@Controller("Poyear_ActivityController")
@RequestMapping("/api/Poyear_Activity")
public class Poyear_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(Poyear_ActivityController.class.getName());

 


	private Poyear_ActivityService Poyear_Activity_service;


	public Poyear_ActivityService get_Poyear_Activity_service() {
		return Poyear_Activity_service;
	}


	@Resource(name="Poyear_ActivityService")
	public void set_Poyear_Activity_service(Poyear_ActivityService Poyear_Activity_service) {
		this.Poyear_Activity_service = Poyear_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Poyear noun into database
	* @param the_Poyear
	*@return Poyear object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Poyear", httpMethod = "POST",notes = "creates a noun of Poyear",response = Poyear.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Poyear" ,headers="Accept=application/json")
    @ResponseBody
	public Poyear create_Poyear(@RequestBody Poyear the_Poyear) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Poyear controller started operation!");

		the_Poyear.setId(null);

		Poyear a_Poyear = Poyear_Activity_service.create_poyear(the_Poyear);

		log.info("Object returned from create_Poyear method !");

 

        return a_Poyear;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Poyear noun into database
	*@param the_Poyear
	*@return Poyearobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Poyear", httpMethod = "PUT",notes = "updates a noun of Poyear",response = Poyear.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Poyear" ,headers="Accept=application/json")
    @ResponseBody
	public Poyear update_Poyear(@RequestBody Poyear the_Poyear) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Poyear controller started operation!");

		Poyear a_Poyear;

		a_Poyear = Poyear_Activity_service.update_poyear(the_Poyear);

		log.info("Object returned from update_Poyear method !");

 

        return a_Poyear;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Poyear noun from  database based on given noun id
	*@param Poyear_id
	*@return Poyearobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Poyear/{Poyear_id}", httpMethod = "GET",notes = "updates a noun of Poyear",response = Poyear.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Poyear/{Poyear_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Poyear search_for_update_Poyear(@PathVariable("Poyear_id")String Poyear_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Poyear controller started operation!");

		Poyear the_Poyear = new Poyear();

		the_Poyear = Poyear_Activity_service.poyear_search_for_update(Poyear_id);

		log.info("Object returned from search_for_update_Poyear method !");

 

        return the_Poyear;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Poyear noun from  database based on given noun id
	*@param Poyear_id
	*@return Poyearobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Poyear/{Poyear_id}", httpMethod = "DELETE",notes = "deletes a noun of Poyear",response = Poyear.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Poyear/{Poyear_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Poyear(@PathVariable("Poyear_id")String  Poyear_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Poyear controller started operation!");

		String service_return_msg = "";

		service_return_msg = Poyear_Activity_service.delete_poyear(Poyear_id);

		log.info("Object returned from delete_Poyear method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Poyear noun from  database
	*
	*@return List of Poyear objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Poyear", httpMethod = "GET",notes = "special search that gets all values of Poyear",response = Poyear.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Poyear" ,headers="Accept=application/json")
    @ResponseBody
	public List<Poyear> get_all_Poyear() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Poyear controller started operation!");

		List<Poyear> Poyear_list = new ArrayList<Poyear>();

		Poyear_list = Poyear_Activity_service.get_all_poyear();

		log.info("Object returned from get_all_Poyear method !");

 

        return Poyear_list;

	}




}