package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.Purpose;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.Purpose_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/Purpose_Activity", description = "Purpose_Activity of Purpose_Activity",produces = "application/json")
@CrossOrigin
@Controller("Purpose_ActivityController")
@RequestMapping("/api/Purpose_Activity")
public class Purpose_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(Purpose_ActivityController.class.getName());

 


	private Purpose_ActivityService Purpose_Activity_service;


	public Purpose_ActivityService get_Purpose_Activity_service() {
		return Purpose_Activity_service;
	}


	@Resource(name="Purpose_ActivityService")
	public void set_Purpose_Activity_service(Purpose_ActivityService Purpose_Activity_service) {
		this.Purpose_Activity_service = Purpose_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Purpose noun into database
	* @param the_Purpose
	*@return Purpose object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Purpose", httpMethod = "POST",notes = "creates a noun of Purpose",response = Purpose.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Purpose" ,headers="Accept=application/json")
    @ResponseBody
	public Purpose create_Purpose(@RequestBody Purpose the_Purpose) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Purpose controller started operation!");

		the_Purpose.setid(null);

		Purpose a_Purpose = Purpose_Activity_service.create_purpose(the_Purpose);

		log.info("Object returned from create_Purpose method !");

 

        return a_Purpose;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Purpose noun into database
	*@param the_Purpose
	*@return Purposeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Purpose", httpMethod = "PUT",notes = "updates a noun of Purpose",response = Purpose.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Purpose" ,headers="Accept=application/json")
    @ResponseBody
	public Purpose update_Purpose(@RequestBody Purpose the_Purpose) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Purpose controller started operation!");

		Purpose a_Purpose;

		a_Purpose = Purpose_Activity_service.update_purpose(the_Purpose);

		log.info("Object returned from update_Purpose method !");

 

        return a_Purpose;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Purpose noun from  database based on given noun id
	*@param Purpose_id
	*@return Purposeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Purpose/{Purpose_id}", httpMethod = "GET",notes = "updates a noun of Purpose",response = Purpose.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Purpose/{Purpose_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Purpose search_for_update_Purpose(@PathVariable("Purpose_id")String Purpose_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Purpose controller started operation!");

		Purpose the_Purpose = new Purpose();

		the_Purpose = Purpose_Activity_service.purpose_search_for_update(Purpose_id);

		log.info("Object returned from search_for_update_Purpose method !");

 

        return the_Purpose;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Purpose noun from  database based on given noun id
	*@param Purpose_id
	*@return Purposeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Purpose/{Purpose_id}", httpMethod = "DELETE",notes = "deletes a noun of Purpose",response = Purpose.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Purpose/{Purpose_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Purpose(@PathVariable("Purpose_id")String  Purpose_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Purpose controller started operation!");

		String service_return_msg = "";

		service_return_msg = Purpose_Activity_service.delete_purpose(Purpose_id);

		log.info("Object returned from delete_Purpose method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Purpose noun from  database
	*
	*@return List of Purpose objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Purpose", httpMethod = "GET",notes = "special search that gets all values of Purpose",response = Purpose.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Purpose" ,headers="Accept=application/json")
    @ResponseBody
	public List<Purpose> get_all_Purpose() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Purpose controller started operation!");

		List<Purpose> Purpose_list = new ArrayList<Purpose>();

		Purpose_list = Purpose_Activity_service.get_all_purpose();

		log.info("Object returned from get_all_Purpose method !");

 

        return Purpose_list;

	}




}