package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.Room;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.Room_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/Room_Default_Activity", description = "Room_Default_Activity of Room_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Room_Default_ActivityController")
@RequestMapping("/api/Room_Default_Activity")
public class Room_Default_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(Room_Default_ActivityController.class.getName());

 


	private Room_Default_ActivityService Room_Default_Activity_service;


	public Room_Default_ActivityService get_Room_Default_Activity_service() {
		return Room_Default_Activity_service;
	}


	@Resource(name="Room_Default_ActivityService")
	public void set_Room_Default_Activity_service(Room_Default_ActivityService Room_Default_Activity_service) {
		this.Room_Default_Activity_service = Room_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Room noun into database
	* @param the_Room
	*@return Room object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Room", httpMethod = "POST",notes = "creates a noun of Room",response = Room.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Room" ,headers="Accept=application/json")
    @ResponseBody
	public Room create_Room(@RequestBody Room the_Room) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Room controller started operation!");

		the_Room.setid(null);

		Room a_Room = Room_Default_Activity_service.create_room(the_Room);

		log.info("Object returned from create_Room method !");

 

        return a_Room;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Room noun into database
	*@param the_Room
	*@return Roomobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Room", httpMethod = "PUT",notes = "updates a noun of Room",response = Room.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Room" ,headers="Accept=application/json")
    @ResponseBody
	public Room update_Room(@RequestBody Room the_Room) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Room controller started operation!");

		Room a_Room;

		a_Room = Room_Default_Activity_service.update_room(the_Room);

		log.info("Object returned from update_Room method !");

 

        return a_Room;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Room noun from  database based on given noun id
	*@param Room_id
	*@return Roomobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Room/{Room_id}", httpMethod = "GET",notes = "updates a noun of Room",response = Room.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Room/{Room_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Room search_for_update_Room(@PathVariable("Room_id")String Room_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Room controller started operation!");

		Room the_Room = new Room();

		the_Room = Room_Default_Activity_service.room_search_for_update(Room_id);

		log.info("Object returned from search_for_update_Room method !");

 

        return the_Room;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Room noun from  database based on given noun id
	*@param Room_id
	*@return Roomobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Room/{Room_id}", httpMethod = "DELETE",notes = "deletes a noun of Room",response = Room.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Room/{Room_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Room(@PathVariable("Room_id")String  Room_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Room controller started operation!");

		String service_return_msg = "";

		service_return_msg = Room_Default_Activity_service.delete_room(Room_id);

		log.info("Object returned from delete_Room method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Room noun from  database
	*
	*@return List of Room objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Room", httpMethod = "GET",notes = "special search that gets all values of Room",response = Room.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Room" ,headers="Accept=application/json")
    @ResponseBody
	public List<Room> get_all_Room() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Room controller started operation!");

		List<Room> Room_list = new ArrayList<Room>();

		Room_list = Room_Default_Activity_service.get_all_room();

		log.info("Object returned from get_all_Room method !");

 

        return Room_list;

	}




}