package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.Sg;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.Sg_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/Sg_Activity", description = "Sg_Activity of Sg_Activity",produces = "application/json")
@CrossOrigin
@Controller("Sg_ActivityController")
@RequestMapping("/api/Sg_Activity")
public class Sg_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(Sg_ActivityController.class.getName());

 


	private Sg_ActivityService Sg_Activity_service;


	public Sg_ActivityService get_Sg_Activity_service() {
		return Sg_Activity_service;
	}


	@Resource(name="Sg_ActivityService")
	public void set_Sg_Activity_service(Sg_ActivityService Sg_Activity_service) {
		this.Sg_Activity_service = Sg_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Sg noun into database
	* @param the_Sg
	*@return Sg object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Sg", httpMethod = "POST",notes = "creates a noun of Sg",response = Sg.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Sg" ,headers="Accept=application/json")
    @ResponseBody
	public Sg create_Sg(@RequestBody Sg the_Sg) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Sg controller started operation!");

		the_Sg.setId(null);

		Sg a_Sg = Sg_Activity_service.create_sg(the_Sg);

		log.info("Object returned from create_Sg method !");

 

        return a_Sg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Sg noun into database
	*@param the_Sg
	*@return Sgobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Sg", httpMethod = "PUT",notes = "updates a noun of Sg",response = Sg.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Sg" ,headers="Accept=application/json")
    @ResponseBody
	public Sg update_Sg(@RequestBody Sg the_Sg) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Sg controller started operation!");

		Sg a_Sg;

		a_Sg = Sg_Activity_service.update_sg(the_Sg);

		log.info("Object returned from update_Sg method !");

 

        return a_Sg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Sg noun from  database based on given noun id
	*@param Sg_id
	*@return Sgobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Sg/{Sg_id}", httpMethod = "GET",notes = "updates a noun of Sg",response = Sg.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Sg/{Sg_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Sg search_for_update_Sg(@PathVariable("Sg_id")String Sg_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Sg controller started operation!");

		Sg the_Sg = new Sg();

		the_Sg = Sg_Activity_service.sg_search_for_update(Sg_id);

		log.info("Object returned from search_for_update_Sg method !");

 

        return the_Sg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Sg noun from  database based on given noun id
	*@param Sg_id
	*@return Sgobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Sg/{Sg_id}", httpMethod = "DELETE",notes = "deletes a noun of Sg",response = Sg.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Sg/{Sg_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Sg(@PathVariable("Sg_id")String  Sg_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Sg controller started operation!");

		String service_return_msg = "";

		service_return_msg = Sg_Activity_service.delete_sg(Sg_id);

		log.info("Object returned from delete_Sg method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Sg noun from  database
	*
	*@return List of Sg objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Sg", httpMethod = "GET",notes = "special search that gets all values of Sg",response = Sg.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Sg" ,headers="Accept=application/json")
    @ResponseBody
	public List<Sg> get_all_Sg() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Sg controller started operation!");

		List<Sg> Sg_list = new ArrayList<Sg>();

		Sg_list = Sg_Activity_service.get_all_sg();

		log.info("Object returned from get_all_Sg method !");

 

        return Sg_list;

	}




}