package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.Srv_adm;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.Srv_adm_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/Srv_adm_Default_Activity", description = "Srv_adm_Default_Activity of Srv_adm_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Srv_adm_Default_ActivityController")
@RequestMapping("/api/Srv_adm_Default_Activity")
public class Srv_adm_Default_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(Srv_adm_Default_ActivityController.class.getName());

 


	private Srv_adm_Default_ActivityService Srv_adm_Default_Activity_service;


	public Srv_adm_Default_ActivityService get_Srv_adm_Default_Activity_service() {
		return Srv_adm_Default_Activity_service;
	}


	@Resource(name="Srv_adm_Default_ActivityService")
	public void set_Srv_adm_Default_Activity_service(Srv_adm_Default_ActivityService Srv_adm_Default_Activity_service) {
		this.Srv_adm_Default_Activity_service = Srv_adm_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Srv_adm noun into database
	* @param the_Srv_adm
	*@return Srv_adm object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Srv_adm", httpMethod = "POST",notes = "creates a noun of Srv_adm",response = Srv_adm.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Srv_adm" ,headers="Accept=application/json")
    @ResponseBody
	public Srv_adm create_Srv_adm(@RequestBody Srv_adm the_Srv_adm) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Srv_adm controller started operation!");

		the_Srv_adm.setId(null);

		Srv_adm a_Srv_adm = Srv_adm_Default_Activity_service.create_srv_adm(the_Srv_adm);

		log.info("Object returned from create_Srv_adm method !");

 

        return a_Srv_adm;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Srv_adm noun into database
	*@param the_Srv_adm
	*@return Srv_admobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Srv_adm", httpMethod = "PUT",notes = "updates a noun of Srv_adm",response = Srv_adm.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Srv_adm" ,headers="Accept=application/json")
    @ResponseBody
	public Srv_adm update_Srv_adm(@RequestBody Srv_adm the_Srv_adm) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Srv_adm controller started operation!");

		Srv_adm a_Srv_adm;

		a_Srv_adm = Srv_adm_Default_Activity_service.update_srv_adm(the_Srv_adm);

		log.info("Object returned from update_Srv_adm method !");

 

        return a_Srv_adm;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Srv_adm noun from  database based on given noun id
	*@param Srv_adm_id
	*@return Srv_admobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Srv_adm/{Srv_adm_id}", httpMethod = "GET",notes = "updates a noun of Srv_adm",response = Srv_adm.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Srv_adm/{Srv_adm_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Srv_adm search_for_update_Srv_adm(@PathVariable("Srv_adm_id")String Srv_adm_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Srv_adm controller started operation!");

		Srv_adm the_Srv_adm = new Srv_adm();

		the_Srv_adm = Srv_adm_Default_Activity_service.srv_adm_search_for_update(Srv_adm_id);

		log.info("Object returned from search_for_update_Srv_adm method !");

 

        return the_Srv_adm;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Srv_adm noun from  database based on given noun id
	*@param Srv_adm_id
	*@return Srv_admobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Srv_adm/{Srv_adm_id}", httpMethod = "DELETE",notes = "deletes a noun of Srv_adm",response = Srv_adm.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Srv_adm/{Srv_adm_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Srv_adm(@PathVariable("Srv_adm_id")String  Srv_adm_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Srv_adm controller started operation!");

		String service_return_msg = "";

		service_return_msg = Srv_adm_Default_Activity_service.delete_srv_adm(Srv_adm_id);

		log.info("Object returned from delete_Srv_adm method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Srv_adm noun from  database
	*
	*@return List of Srv_adm objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Srv_adm", httpMethod = "GET",notes = "special search that gets all values of Srv_adm",response = Srv_adm.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Srv_adm" ,headers="Accept=application/json")
    @ResponseBody
	public List<Srv_adm> get_all_Srv_adm() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Srv_adm controller started operation!");

		List<Srv_adm> Srv_adm_list = new ArrayList<Srv_adm>();

		Srv_adm_list = Srv_adm_Default_Activity_service.get_all_srv_adm();

		log.info("Object returned from get_all_Srv_adm method !");

 

        return Srv_adm_list;

	}




}