import { Component, OnInit, ViewChild, ViewContainerRef } from '@angular/core';
import { Router } from '@angular/router';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
import { ToastsManager } from 'ng2-toastr/ng2-toastr';
import { AssetregisterbookformService } from './assetregisterbookform.service';
import { IAssetregisterbookform } from './assetregisterbookform';

@Component({
    moduleId: module.id,
    templateUrl: 'abrscreeneng.component.html'
})
export class ABRScreenengComponent implements OnInit {
  private assetregisterbookform: IAssetregisterbookform =  {
                id: 0,
                new_status: '',
                floor_number: '',
                lock_code: '',
                project_name: '',
                type: '',
                supply: '',
                infra_own: '',
                ol1_1: '',
                dact_on: '',
                sup_vendor: '',
                new_location: '',
                dram: '',
                isdn: '',
                new_alternateid: '',
                wty_end_date: '',
                acc_no: '',
                ins_expiry_date: '',
                census_reason: '',
                model: '',
                lvd: '',
                per: '',
                dispwty_start_date: '',
                new_email: '',
                dispinst_date: '',
                period: '',
                remk: '',
                new_joiningdate: '',
                ip: '',
                new_entity: '',
                processor: '',
                ram_initial: '',
                new_jobtype: '',
                ar: '',
                usedas: '',
                new_designation: '',
                new_los: '',
                inv_date: '',
                inv_currency: '',
                carepack: '',
                doa: '',
                doc: '',
                created_by: '',
                application1: '',
                flash: '',
                status: '',
                end_date: '',
                ins_policy_no: '',
                loc: '',
                hyper_1: '',
                hdd1: '',
                scan: '',
                disppo_date: '',
                census_remarks: '',
                rack1: '',
                dact_type: false,
                sg: '',
                identity: '',
                erd: '',
                h_type: '',
                sl: '',
                amc_start_date: '',
                currency: '',
                sp: '',
                start_date: '',
                approver: '',
                ins_com_name: '',
                po_date: '',
                po_ref_no: '',
                file_no: '',
                amc_end_date: '',
                dispwty_end_date: '',
                new_gender: '',
                dispins_expiry_date: '',
                dat: '',
                ucode1: '',
                hdd_initial: '',
                allocation_form_no: '',
                serial1: '',
                esn: '',
                po_entity: '',
                wty_status: '',
                census_count: '',
                ehdate: '',
                office: '',
                dispinv_date: '',
                bill_entity: '',
                model_no: '',
                ins_status: '',
                mode: '',
                acce_1: '',
                dc1: false,
                pin: '',
                doa1: '',
                cpd: '',
                pstn: '',
                mac_add: '',
                inst_date: '',
                wty_terms: '',
                oprn_grp: '',
                srv_own: '',
                syssteward: '',
                hyper: false,
                asset_number: '',
                ddate: '',
                type2: false,
                created_on: '',
                last: '',
                dispdoa1: '',
                payment_start_date: '',
                cpu: '',
                project_code: '',
                new_department: '',
                shelf: '',
                ethernet: '',
                delivery_date: '',
                dact_on_3: '',
                remarks_1: '',
                dact_on_2: '',
                inv_amt: '',
                dact_on_1: '',
                port: '',
                new_jobmode: '',
                seat_number: '',
                inv_vendor: '',
                eheditor: '',
                engineer_1: '',
                fc: '',
                connection: false,
                inv_no: '',
                catrige_no: '',
                collected_from: '',
                srv_adm: '',
                code: '',
                new_subsbu: '',
                config: '',
                loc5: '',
                airtelno: '',
                hdd: '',
                fr: '',
                ol2_1: '',
                speed: '',
                wty_start_date: '',
                disperd: '',
                printer_type: false,
                ol2: '',
                ram1: '',
                ol1: '',
                amc_terms: '',
                new_orbitid: '',
                data_limit: '',
                make: '',
                lock_sl: '',
                new_jobfunction: '',
                new_name: '',
                ins_renewal: '',
                rack: '',
                net_cat: '',
                cost: '',
                ract_on_2: '',
                os: '',
                ract_on_1: '',
                ract_on_3: '',
                new_sbu: '',
                mobile: '',
                ins_value: '',
                adaptor: '',
                purpose: '',
                location1: '',
                monitor: false,
                po_year: '',
                ip_1: '',
                date2: '',
                ios: '',
                date1: '',
                engineer: '',
                edor: '',
                room: '',
                rental: '',
                application: '',
                serial: '',
                data_type: '',
                category: '',
                remarks: '',
                host_name: '',
                ram: ''};;

  constructor(private router: Router, public toastr: ToastsManager, vcr: ViewContainerRef, private assetregisterbookformservice: AssetregisterbookformService) { 
    this.toastr.setRootViewContainerRef(vcr);
  }

  ngOnInit() {
  }



}