import { Component, OnInit, ViewChild, ViewContainerRef } from '@angular/core';
import { Router } from '@angular/router';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
import { ToastsManager } from 'ng2-toastr/ng2-toastr';
import { AssetregisterbookformService } from './assetregisterbookform.service';
import { IAssetregisterbookform } from './assetregisterbookform';

@Component({
    moduleId: module.id,
    templateUrl: 'assetregisterbookscreentwo_2eng.component.html'
})
export class AssetRegisterBookScreenTwo_2engComponent implements OnInit {
  private assetregisterbookform: IAssetregisterbookform ;/*= {
  	id: 0,
  	invoiceamount: '',
  	iosversion: '',
  	despatchdate: '',
  	initialhddgb: '',
  	installationdate: '',
  	policynumber: '',
  	officelocation: '',
  	serverowner: '',
  	vendorname: '',
  	seconddeactivationdate: '',
  	invoicedate: '',
  	 pur_currency: '',
    inv_currency: '',
  	dram: '',
  	firstreactivationdate: '',
  	serveradministrator: '',
  	status: '',
  	createdon: '',
  	lastmodifiedon: '',
  	fixedcost: '',
  	hostname: '',
  	billingentity: '',
  	flash: '',
  	thirddeactivationdate: '',
  	dateofallocaiton: '',
  	projectname: '',
  	initialramgb: '',
  	enddate: '',
  	seatno: '',
  	amcterms: '',
  	cpuspeedmhz: '',
  	hypervserver: '',
  	application: '',
  	networkcategoryvlan: '',
  	renewalrequired: '',
  	lnid: '',
  	scancopyofusersigneddocument: '',
  	presentramgb: '',
  	processor: '',
  	hypervservername: '',
  	systemsteward: '',
  	pofinancialyear: '',
  	unitcost: '',
  	invoicenumber: '',
  	noofethernetport: '',
  	dataclassification: '',
  	amcstartdate: '',
  	thirdreactivationdate: '',
  	servicepack: '',
  	connection: '',
  	carepackno: '',
  	allocationformno: '',
  	permanentdeactivationdate: '',
  	engineersname: '',
  	type: '',
  	dateofassigmentoftheserver: '',
  	secondreactivationdate: '',
  	gtsfileno: '',
  	countedforcensus: '',
  	dateofcommunication: '',
  	lastreturnedby: '',
  	rackno: '',
  	expectedreleasedate: '',
  	modeofuse: '',
  	noofisdnport: '',
  	approverprojectmanager: '',
  	datacardtype: '',
  	ipaddress: '',
  	startdate: '',
  	remarks: '',
  	contractperiodduration: '',
  	policyenddate: '',
  	periodinmonthfreerentalcharges: '',
  	oprn_grp: '',
  	deliverydate: '',
  	lastmodifiedby: '',
  	saferguardinstalled: '',
  	porefno: '',
  	terms: '',
  	presenthddgb: '',
  	otherinformation: '',
  	amcenddate: '',
  	infrastructureowner: '',
  	functionality: '',
  	despatchfromkolkatato: '',
  	insuredvalue: '',
  	createdby: '',
  	_class: '',
  	deactivationtype: '',
  	expecteddateofreturn: '',
  	rentalplan: '',
  	noofserialport: '',
  	category: '',
  	advancedrental: '',
  	firstdeactivationdate: '',
  	supportvendor: '',
  	shelfno: '',
  	accountcafnumber: '',
  	accessories: '',
  	mobilenumber: '',
  	buliderfloor: '',
  	freerental: '',
  	paymentstartdatewithrentalchages: '',
  	datatransferlimit: '',
  	os: '',
  	macaddress: '',
  	reasonfornotcount: '',
  	podate: '',
  	date2: '',
  	date1: '',
  	poentity: '',
  	suppliedbygtl: '',
  	hardwaretype: '',
  	companyname: '',
  	noofpstnport: '',
  	projectcode: '',
  	serverimporance: '',
  	allocatedfrom: '',
  	insurancestatus: '',
  	noofcpu: '',
  	hdddetails: '',
  	datdltingb: '',
  	ramdetails: '',
  	modelno: '',
  	speed: '',
  	portno: '',
  	catrigeno: ''}
  ;
*/
  constructor(private router: Router, public toastr: ToastsManager, vcr: ViewContainerRef, private assetregisterbookformservice: AssetregisterbookformService) { 
    this.toastr.setRootViewContainerRef(vcr);
    this.assetregisterbookform = assetregisterbookformservice.IAssetregisterbookform;
  }

  ngOnInit() {
  }



}