package com.AssetRegisterBook.domain.core;

import org.springframework.data.annotation.Id;

import org.springframework.data.couchbase.core.mapping.Document;

import org.springframework.data.annotation.TypeAlias;

import org.springframework.data.couchbase.core.mapping.Field;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonProperty;
@Document
@TypeAlias("os")

@ApiModel( value = "OS", description = "OS" )
public class OS  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
@JsonProperty("id")
	@Id 
 
 	private	String Id;



	@ApiModelProperty( value = "created date", required = true )
@JsonProperty("created_date")
	@Field
 	private	String Created_date;



	@ApiModelProperty( value = "created by value", required = true )
@JsonProperty("created_by")
	@Field
 	private	long Created_by;



	@ApiModelProperty( value = "updated date", required = true )
@JsonProperty("updated_date")
	@Field
 	private	String Updated_date;



	@ApiModelProperty( value = "updated by value", required = true )
@JsonProperty("updated_by")
	@Field
 	private	long Updated_by;



	@ApiModelProperty( value = "description", required = true )
@JsonProperty("osname")
	@Field("OSName")
 	private	String OSName;



	@ApiModelProperty( value = "description", required = true )
@JsonProperty("osdescription")
	@Field("OsDescription")
 	private	String OsDescription;




	public void setId(String Id) {
		this.Id = Id;
	}


	public String getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setOSName(String OSName) {
		this.OSName = OSName;
	}


	public String getOSName() {
		return OSName;
	}

	public void setOsDescription(String OsDescription) {
		this.OsDescription = OsDescription;
	}


	public String getOsDescription() {
		return OsDescription;
	}




}