server:
  port: 8080

security:
  basic:
    enabled: false

entitymanager:
  packagesToScan: com.AssetRegisterBook.*



couchbase:
  cluster:
    ip: localhost
    bucket: ARBDhina
    username: Administrator
    password: 211218
    db:
      password: 


 
