package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.Application;

import com.AssetRegisterBook.dao.couchbase.Application_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Application_ActivityService")
public class Application_ActivityService   {
private static Logger log = Logger.getLogger(Application_ActivityService.class.getName());

	private Application_ActivityDao Application_Activity_dao;


	public Application_ActivityDao get_Application_Activity_dao() {
		return Application_Activity_dao;
	}


	@Resource(name="Application_ActivityDao")
	public void set_Application_Activity_dao(Application_ActivityDao Application_Activity_dao) {
		this.Application_Activity_dao = Application_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Application noun into database
	*@param Application
	*@param user
	*@return the_Application object will return
	*@throws Exception
	*/

	public Application create_application(Application Application) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_application service operation started !");

		try{
			Application the_Application;

			the_Application = Application_Activity_dao.create_application(Application);

 			log.info(" Object returned from create_application  service method !");
			return the_Application;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_application service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Application noun into database
	*@param Application
	*@param user
	*@return the_Application object will return
	*@throws Exception
	*/

	public Application update_application(Application Application) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_application service operation started !");

		try{
			Application the_Application;

			the_Application = Application_Activity_dao.update_application(Application);

 			log.info(" Object returned from update_application  service method !");
			return the_Application;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_application service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Application noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Application object will return
	*@throws Exception
	*/

	public Application application_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("application_search_for_update service operation started !");

		try{
			Application the_Application;

			the_Application = Application_Activity_dao.application_search_for_update(id);

 			log.info(" Object returned from application_search_for_update  service method !");
			return the_Application;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("application_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Application noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Application id deleted based on id
	*@throws Exception
	*/

	public String  delete_application(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_application service operation started !");

		try{
			String method_return_message;

			method_return_message = Application_Activity_dao.delete_application(id);

 			log.info(" Object returned from delete_application  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_application service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Application noun from  database
	*
	*
	*@return List of Application object will return
	*@throws Exception
	*/

	public ArrayList<Application> get_all_application() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Application> Application_list;

			Application_list = Application_Activity_dao.get_all_application();

 			log.info(" Object returned from   service method !");
			return Application_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}