package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.InvoiceVendor;

import com.AssetRegisterBook.dao.couchbase.InvoiceVendor_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("InvoiceVendor_ActivityService")
public class InvoiceVendor_ActivityService   {
private static Logger log = Logger.getLogger(InvoiceVendor_ActivityService.class.getName());

	private InvoiceVendor_ActivityDao InvoiceVendor_Activity_dao;


	public InvoiceVendor_ActivityDao get_InvoiceVendor_Activity_dao() {
		return InvoiceVendor_Activity_dao;
	}


	@Resource(name="InvoiceVendor_ActivityDao")
	public void set_InvoiceVendor_Activity_dao(InvoiceVendor_ActivityDao InvoiceVendor_Activity_dao) {
		this.InvoiceVendor_Activity_dao = InvoiceVendor_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  InvoiceVendor noun into database
	*@param InvoiceVendor
	*@param user
	*@return the_InvoiceVendor object will return
	*@throws Exception
	*/

	public InvoiceVendor create_invoicevendor(InvoiceVendor InvoiceVendor) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_invoicevendor service operation started !");

		try{
			InvoiceVendor the_InvoiceVendor;

			the_InvoiceVendor = InvoiceVendor_Activity_dao.create_invoicevendor(InvoiceVendor);

 			log.info(" Object returned from create_invoicevendor  service method !");
			return the_InvoiceVendor;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_invoicevendor service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  InvoiceVendor noun into database
	*@param InvoiceVendor
	*@param user
	*@return the_InvoiceVendor object will return
	*@throws Exception
	*/

	public InvoiceVendor update_invoicevendor(InvoiceVendor InvoiceVendor) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_invoicevendor service operation started !");

		try{
			InvoiceVendor the_InvoiceVendor;

			the_InvoiceVendor = InvoiceVendor_Activity_dao.update_invoicevendor(InvoiceVendor);

 			log.info(" Object returned from update_invoicevendor  service method !");
			return the_InvoiceVendor;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_invoicevendor service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  InvoiceVendor noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_InvoiceVendor object will return
	*@throws Exception
	*/

	public InvoiceVendor invoicevendor_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("invoicevendor_search_for_update service operation started !");

		try{
			InvoiceVendor the_InvoiceVendor;

			the_InvoiceVendor = InvoiceVendor_Activity_dao.invoicevendor_search_for_update(id);

 			log.info(" Object returned from invoicevendor_search_for_update  service method !");
			return the_InvoiceVendor;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("invoicevendor_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  InvoiceVendor noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_InvoiceVendor id deleted based on id
	*@throws Exception
	*/

	public String  delete_invoicevendor(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_invoicevendor service operation started !");

		try{
			String method_return_message;

			method_return_message = InvoiceVendor_Activity_dao.delete_invoicevendor(id);

 			log.info(" Object returned from delete_invoicevendor  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_invoicevendor service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  InvoiceVendor noun from  database
	*
	*
	*@return List of InvoiceVendor object will return
	*@throws Exception
	*/

	public ArrayList<InvoiceVendor> get_all_invoicevendor() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<InvoiceVendor> InvoiceVendor_list;

			InvoiceVendor_list = InvoiceVendor_Activity_dao.get_all_invoicevendor();

 			log.info(" Object returned from   service method !");
			return InvoiceVendor_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}