package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.Poentity;

import com.AssetRegisterBook.dao.couchbase.Poentity_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Poentity_ActivityService")
public class Poentity_ActivityService   {
private static Logger log = Logger.getLogger(Poentity_ActivityService.class.getName());

	private Poentity_ActivityDao Poentity_Activity_dao;


	public Poentity_ActivityDao get_Poentity_Activity_dao() {
		return Poentity_Activity_dao;
	}


	@Resource(name="Poentity_ActivityDao")
	public void set_Poentity_Activity_dao(Poentity_ActivityDao Poentity_Activity_dao) {
		this.Poentity_Activity_dao = Poentity_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Poentity noun into database
	*@param Poentity
	*@param user
	*@return the_Poentity object will return
	*@throws Exception
	*/

	public Poentity create_poentity(Poentity Poentity) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_poentity service operation started !");

		try{
			Poentity the_Poentity;

			the_Poentity = Poentity_Activity_dao.create_poentity(Poentity);

 			log.info(" Object returned from create_poentity  service method !");
			return the_Poentity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_poentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Poentity noun into database
	*@param Poentity
	*@param user
	*@return the_Poentity object will return
	*@throws Exception
	*/

	public Poentity update_poentity(Poentity Poentity) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_poentity service operation started !");

		try{
			Poentity the_Poentity;

			the_Poentity = Poentity_Activity_dao.update_poentity(Poentity);

 			log.info(" Object returned from update_poentity  service method !");
			return the_Poentity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_poentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Poentity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poentity object will return
	*@throws Exception
	*/

	public Poentity poentity_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("poentity_search_for_update service operation started !");

		try{
			Poentity the_Poentity;

			the_Poentity = Poentity_Activity_dao.poentity_search_for_update(id);

 			log.info(" Object returned from poentity_search_for_update  service method !");
			return the_Poentity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("poentity_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Poentity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poentity id deleted based on id
	*@throws Exception
	*/

	public String  delete_poentity(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_poentity service operation started !");

		try{
			String method_return_message;

			method_return_message = Poentity_Activity_dao.delete_poentity(id);

 			log.info(" Object returned from delete_poentity  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_poentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Poentity noun from  database
	*
	*
	*@return List of Poentity object will return
	*@throws Exception
	*/

	public ArrayList<Poentity> get_all_poentity() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Poentity> Poentity_list;

			Poentity_list = Poentity_Activity_dao.get_all_poentity();

 			log.info(" Object returned from   service method !");
			return Poentity_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}