package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.Sg;

import com.AssetRegisterBook.dao.couchbase.Sg_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Sg_ActivityService")
public class Sg_ActivityService   {
private static Logger log = Logger.getLogger(Sg_ActivityService.class.getName());

	private Sg_ActivityDao Sg_Activity_dao;


	public Sg_ActivityDao get_Sg_Activity_dao() {
		return Sg_Activity_dao;
	}


	@Resource(name="Sg_ActivityDao")
	public void set_Sg_Activity_dao(Sg_ActivityDao Sg_Activity_dao) {
		this.Sg_Activity_dao = Sg_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Sg noun into database
	*@param Sg
	*@param user
	*@return the_Sg object will return
	*@throws Exception
	*/

	public Sg create_sg(Sg Sg) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_sg service operation started !");

		try{
			Sg the_Sg;

			the_Sg = Sg_Activity_dao.create_sg(Sg);

 			log.info(" Object returned from create_sg  service method !");
			return the_Sg;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_sg service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Sg noun into database
	*@param Sg
	*@param user
	*@return the_Sg object will return
	*@throws Exception
	*/

	public Sg update_sg(Sg Sg) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_sg service operation started !");

		try{
			Sg the_Sg;

			the_Sg = Sg_Activity_dao.update_sg(Sg);

 			log.info(" Object returned from update_sg  service method !");
			return the_Sg;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_sg service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Sg noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Sg object will return
	*@throws Exception
	*/

	public Sg sg_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("sg_search_for_update service operation started !");

		try{
			Sg the_Sg;

			the_Sg = Sg_Activity_dao.sg_search_for_update(id);

 			log.info(" Object returned from sg_search_for_update  service method !");
			return the_Sg;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("sg_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Sg noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Sg id deleted based on id
	*@throws Exception
	*/

	public String  delete_sg(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_sg service operation started !");

		try{
			String method_return_message;

			method_return_message = Sg_Activity_dao.delete_sg(id);

 			log.info(" Object returned from delete_sg  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_sg service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Sg noun from  database
	*
	*
	*@return List of Sg object will return
	*@throws Exception
	*/

	public ArrayList<Sg> get_all_sg() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Sg> Sg_list;

			Sg_list = Sg_Activity_dao.get_all_sg();

 			log.info(" Object returned from   service method !");
			return Sg_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}