package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.ApproverOrProjectManager;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.ApproverOrProjectManagerService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/ApproverOrProjectManager", description = "ApproverOrProjectManager of ApproverOrProjectManager",produces = "application/json")
@CrossOrigin
@Controller("ApproverOrProjectManagerController")
@RequestMapping("/api/ApproverOrProjectManager")
public class ApproverOrProjectManagerController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(ApproverOrProjectManagerController.class.getName());

 


	private ApproverOrProjectManagerService ApproverOrProjectManager_service;


	public ApproverOrProjectManagerService get_ApproverOrProjectManager_service() {
		return ApproverOrProjectManager_service;
	}


	@Resource(name="ApproverOrProjectManagerService")
	public void set_ApproverOrProjectManager_service(ApproverOrProjectManagerService ApproverOrProjectManager_service) {
		this.ApproverOrProjectManager_service = ApproverOrProjectManager_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  ApproverOrProjectManager noun into database
	* @param the_ApproverOrProjectManager
	*@return ApproverOrProjectManager object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_ApproverOrProjectManager", httpMethod = "POST",notes = "creates a noun of ApproverOrProjectManager",response = ApproverOrProjectManager.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_ApproverOrProjectManager" ,headers="Accept=application/json")
    @ResponseBody
	public ApproverOrProjectManager create_ApproverOrProjectManager(@RequestBody ApproverOrProjectManager the_ApproverOrProjectManager) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_ApproverOrProjectManager controller started operation!");

		the_ApproverOrProjectManager.setId(null);

		ApproverOrProjectManager a_ApproverOrProjectManager = ApproverOrProjectManager_service.create_approverorprojectmanager(the_ApproverOrProjectManager);

		log.info("Object returned from create_ApproverOrProjectManager method !");

 

        return a_ApproverOrProjectManager;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  ApproverOrProjectManager noun into database
	*@param the_ApproverOrProjectManager
	*@return ApproverOrProjectManagerobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_ApproverOrProjectManager", httpMethod = "PUT",notes = "updates a noun of ApproverOrProjectManager",response = ApproverOrProjectManager.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_ApproverOrProjectManager" ,headers="Accept=application/json")
    @ResponseBody
	public ApproverOrProjectManager update_ApproverOrProjectManager(@RequestBody ApproverOrProjectManager the_ApproverOrProjectManager) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_ApproverOrProjectManager controller started operation!");

		ApproverOrProjectManager a_ApproverOrProjectManager;

		a_ApproverOrProjectManager = ApproverOrProjectManager_service.update_approverorprojectmanager(the_ApproverOrProjectManager);

		log.info("Object returned from update_ApproverOrProjectManager method !");

 

        return a_ApproverOrProjectManager;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  ApproverOrProjectManager noun from  database based on given noun id
	*@param ApproverOrProjectManager_id
	*@return ApproverOrProjectManagerobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_ApproverOrProjectManager/{ApproverOrProjectManager_id}", httpMethod = "GET",notes = "updates a noun of ApproverOrProjectManager",response = ApproverOrProjectManager.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_ApproverOrProjectManager/{ApproverOrProjectManager_id}" ,headers="Accept=application/json")
    @ResponseBody
	public ApproverOrProjectManager search_for_update_ApproverOrProjectManager(@PathVariable("ApproverOrProjectManager_id")String ApproverOrProjectManager_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_ApproverOrProjectManager controller started operation!");

		ApproverOrProjectManager the_ApproverOrProjectManager = new ApproverOrProjectManager();

		the_ApproverOrProjectManager = ApproverOrProjectManager_service.approverorprojectmanager_search_for_update(ApproverOrProjectManager_id);

		log.info("Object returned from search_for_update_ApproverOrProjectManager method !");

 

        return the_ApproverOrProjectManager;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  ApproverOrProjectManager noun from  database based on given noun id
	*@param ApproverOrProjectManager_id
	*@return ApproverOrProjectManagerobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_ApproverOrProjectManager/{ApproverOrProjectManager_id}", httpMethod = "DELETE",notes = "deletes a noun of ApproverOrProjectManager",response = ApproverOrProjectManager.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_ApproverOrProjectManager/{ApproverOrProjectManager_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_ApproverOrProjectManager(@PathVariable("ApproverOrProjectManager_id")String  ApproverOrProjectManager_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_ApproverOrProjectManager controller started operation!");

		String service_return_msg = "";

		service_return_msg = ApproverOrProjectManager_service.delete_approverorprojectmanager(ApproverOrProjectManager_id);

		log.info("Object returned from delete_ApproverOrProjectManager method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  ApproverOrProjectManager noun from  database
	*
	*@return List of ApproverOrProjectManager objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_ApproverOrProjectManager", httpMethod = "GET",notes = "special search that gets all values of ApproverOrProjectManager",response = ApproverOrProjectManager.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_ApproverOrProjectManager" ,headers="Accept=application/json")
    @ResponseBody
	public List<ApproverOrProjectManager> get_all_ApproverOrProjectManager() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_ApproverOrProjectManager controller started operation!");

		List<ApproverOrProjectManager> ApproverOrProjectManager_list = new ArrayList<ApproverOrProjectManager>();

		ApproverOrProjectManager_list = ApproverOrProjectManager_service.get_all_approverorprojectmanager();

		log.info("Object returned from get_all_ApproverOrProjectManager method !");

 

        return ApproverOrProjectManager_list;

	}




}