package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.BuildingOrFloor;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.BuildingOrFloorActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/BuildingOrFloorActivity", description = "BuildingOrFloorActivity of BuildingOrFloorActivity",produces = "application/json")
@CrossOrigin
@Controller("BuildingOrFloorActivityController")
@RequestMapping("/api/BuildingOrFloorActivity")
public class BuildingOrFloorActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(BuildingOrFloorActivityController.class.getName());

 


	private BuildingOrFloorActivityService BuildingOrFloorActivity_service;


	public BuildingOrFloorActivityService get_BuildingOrFloorActivity_service() {
		return BuildingOrFloorActivity_service;
	}


	@Resource(name="BuildingOrFloorActivityService")
	public void set_BuildingOrFloorActivity_service(BuildingOrFloorActivityService BuildingOrFloorActivity_service) {
		this.BuildingOrFloorActivity_service = BuildingOrFloorActivity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  BuildingOrFloor noun into database
	* @param the_BuildingOrFloor
	*@return BuildingOrFloor object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_BuildingOrFloor", httpMethod = "POST",notes = "creates a noun of BuildingOrFloor",response = BuildingOrFloor.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_BuildingOrFloor" ,headers="Accept=application/json")
    @ResponseBody
	public BuildingOrFloor create_BuildingOrFloor(@RequestBody BuildingOrFloor the_BuildingOrFloor) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_BuildingOrFloor controller started operation!");

		the_BuildingOrFloor.setId(null);

		BuildingOrFloor a_BuildingOrFloor = BuildingOrFloorActivity_service.create_buildingorfloor(the_BuildingOrFloor);

		log.info("Object returned from create_BuildingOrFloor method !");

 

        return a_BuildingOrFloor;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  BuildingOrFloor noun into database
	*@param the_BuildingOrFloor
	*@return BuildingOrFloorobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_BuildingOrFloor", httpMethod = "PUT",notes = "updates a noun of BuildingOrFloor",response = BuildingOrFloor.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_BuildingOrFloor" ,headers="Accept=application/json")
    @ResponseBody
	public BuildingOrFloor update_BuildingOrFloor(@RequestBody BuildingOrFloor the_BuildingOrFloor) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_BuildingOrFloor controller started operation!");

		BuildingOrFloor a_BuildingOrFloor;

		a_BuildingOrFloor = BuildingOrFloorActivity_service.update_buildingorfloor(the_BuildingOrFloor);

		log.info("Object returned from update_BuildingOrFloor method !");

 

        return a_BuildingOrFloor;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  BuildingOrFloor noun from  database based on given noun id
	*@param BuildingOrFloor_id
	*@return BuildingOrFloorobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_BuildingOrFloor/{BuildingOrFloor_id}", httpMethod = "GET",notes = "updates a noun of BuildingOrFloor",response = BuildingOrFloor.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_BuildingOrFloor/{BuildingOrFloor_id}" ,headers="Accept=application/json")
    @ResponseBody
	public BuildingOrFloor search_for_update_BuildingOrFloor(@PathVariable("BuildingOrFloor_id")String BuildingOrFloor_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_BuildingOrFloor controller started operation!");

		BuildingOrFloor the_BuildingOrFloor = new BuildingOrFloor();

		the_BuildingOrFloor = BuildingOrFloorActivity_service.buildingorfloor_search_for_update(BuildingOrFloor_id);

		log.info("Object returned from search_for_update_BuildingOrFloor method !");

 

        return the_BuildingOrFloor;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  BuildingOrFloor noun from  database based on given noun id
	*@param BuildingOrFloor_id
	*@return BuildingOrFloorobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_BuildingOrFloor/{BuildingOrFloor_id}", httpMethod = "DELETE",notes = "deletes a noun of BuildingOrFloor",response = BuildingOrFloor.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_BuildingOrFloor/{BuildingOrFloor_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_BuildingOrFloor(@PathVariable("BuildingOrFloor_id")String  BuildingOrFloor_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_BuildingOrFloor controller started operation!");

		String service_return_msg = "";

		service_return_msg = BuildingOrFloorActivity_service.delete_buildingorfloor(BuildingOrFloor_id);

		log.info("Object returned from delete_BuildingOrFloor method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  BuildingOrFloor noun from  database
	*
	*@return List of BuildingOrFloor objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_BuildingOrFloor", httpMethod = "GET",notes = "special search that gets all values of BuildingOrFloor",response = BuildingOrFloor.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_BuildingOrFloor" ,headers="Accept=application/json")
    @ResponseBody
	public List<BuildingOrFloor> get_all_BuildingOrFloor() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_BuildingOrFloor controller started operation!");

		List<BuildingOrFloor> BuildingOrFloor_list = new ArrayList<BuildingOrFloor>();

		BuildingOrFloor_list = BuildingOrFloorActivity_service.get_all_buildingorfloor();

		log.info("Object returned from get_all_BuildingOrFloor method !");

 

        return BuildingOrFloor_list;

	}




}