package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.CensusCount;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.CensusCountService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/CensusCount", description = "CensusCount of CensusCount",produces = "application/json")
@CrossOrigin
@Controller("CensusCountController")
@RequestMapping("/api/CensusCount")
public class CensusCountController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(CensusCountController.class.getName());

 


	private CensusCountService CensusCount_service;


	public CensusCountService get_CensusCount_service() {
		return CensusCount_service;
	}


	@Resource(name="CensusCountService")
	public void set_CensusCount_service(CensusCountService CensusCount_service) {
		this.CensusCount_service = CensusCount_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  CensusCount noun into database
	* @param the_CensusCount
	*@return CensusCount object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_CensusCount", httpMethod = "POST",notes = "creates a noun of CensusCount",response = CensusCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_CensusCount" ,headers="Accept=application/json")
    @ResponseBody
	public CensusCount create_CensusCount(@RequestBody CensusCount the_CensusCount) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_CensusCount controller started operation!");

		the_CensusCount.setId(null);

		CensusCount a_CensusCount = CensusCount_service.create_censuscount(the_CensusCount);

		log.info("Object returned from create_CensusCount method !");

 

        return a_CensusCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  CensusCount noun into database
	*@param the_CensusCount
	*@return CensusCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_CensusCount", httpMethod = "PUT",notes = "updates a noun of CensusCount",response = CensusCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_CensusCount" ,headers="Accept=application/json")
    @ResponseBody
	public CensusCount update_CensusCount(@RequestBody CensusCount the_CensusCount) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_CensusCount controller started operation!");

		CensusCount a_CensusCount;

		a_CensusCount = CensusCount_service.update_censuscount(the_CensusCount);

		log.info("Object returned from update_CensusCount method !");

 

        return a_CensusCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  CensusCount noun from  database based on given noun id
	*@param CensusCount_id
	*@return CensusCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_CensusCount/{CensusCount_id}", httpMethod = "GET",notes = "updates a noun of CensusCount",response = CensusCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_CensusCount/{CensusCount_id}" ,headers="Accept=application/json")
    @ResponseBody
	public CensusCount search_for_update_CensusCount(@PathVariable("CensusCount_id")String CensusCount_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_CensusCount controller started operation!");

		CensusCount the_CensusCount = new CensusCount();

		the_CensusCount = CensusCount_service.censuscount_search_for_update(CensusCount_id);

		log.info("Object returned from search_for_update_CensusCount method !");

 

        return the_CensusCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  CensusCount noun from  database based on given noun id
	*@param CensusCount_id
	*@return CensusCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_CensusCount/{CensusCount_id}", httpMethod = "DELETE",notes = "deletes a noun of CensusCount",response = CensusCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_CensusCount/{CensusCount_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_CensusCount(@PathVariable("CensusCount_id")String  CensusCount_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_CensusCount controller started operation!");

		String service_return_msg = "";

		service_return_msg = CensusCount_service.delete_censuscount(CensusCount_id);

		log.info("Object returned from delete_CensusCount method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  CensusCount noun from  database
	*
	*@return List of CensusCount objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_CensusCount", httpMethod = "GET",notes = "special search that gets all values of CensusCount",response = CensusCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_CensusCount" ,headers="Accept=application/json")
    @ResponseBody
	public List<CensusCount> get_all_CensusCount() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_CensusCount controller started operation!");

		List<CensusCount> CensusCount_list = new ArrayList<CensusCount>();

		CensusCount_list = CensusCount_service.get_all_censuscount();

		log.info("Object returned from get_all_CensusCount method !");

 

        return CensusCount_list;

	}




}