package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.OS;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.OS_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/OS_Activity", description = "OS_Activity of OS_Activity",produces = "application/json")
@CrossOrigin
@Controller("OS_ActivityController")
@RequestMapping("/api/OS_Activity")
public class OS_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(OS_ActivityController.class.getName());

 


	private OS_ActivityService OS_Activity_service;


	public OS_ActivityService get_OS_Activity_service() {
		return OS_Activity_service;
	}


	@Resource(name="OS_ActivityService")
	public void set_OS_Activity_service(OS_ActivityService OS_Activity_service) {
		this.OS_Activity_service = OS_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  OS noun into database
	* @param the_OS
	*@return OS object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_OS", httpMethod = "POST",notes = "creates a noun of OS",response = OS.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_OS" ,headers="Accept=application/json")
    @ResponseBody
	public OS create_OS(@RequestBody OS the_OS) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_OS controller started operation!");

		the_OS.setId(null);

		OS a_OS = OS_Activity_service.create_os(the_OS);

		log.info("Object returned from create_OS method !");

 

        return a_OS;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  OS noun into database
	*@param the_OS
	*@return OSobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_OS", httpMethod = "PUT",notes = "updates a noun of OS",response = OS.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_OS" ,headers="Accept=application/json")
    @ResponseBody
	public OS update_OS(@RequestBody OS the_OS) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_OS controller started operation!");

		OS a_OS;

		a_OS = OS_Activity_service.update_os(the_OS);

		log.info("Object returned from update_OS method !");

 

        return a_OS;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  OS noun from  database based on given noun id
	*@param OS_id
	*@return OSobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_OS/{OS_id}", httpMethod = "GET",notes = "updates a noun of OS",response = OS.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_OS/{OS_id}" ,headers="Accept=application/json")
    @ResponseBody
	public OS search_for_update_OS(@PathVariable("OS_id")String OS_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_OS controller started operation!");

		OS the_OS = new OS();

		the_OS = OS_Activity_service.os_search_for_update(OS_id);

		log.info("Object returned from search_for_update_OS method !");

 

        return the_OS;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  OS noun from  database based on given noun id
	*@param OS_id
	*@return OSobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_OS/{OS_id}", httpMethod = "DELETE",notes = "deletes a noun of OS",response = OS.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_OS/{OS_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_OS(@PathVariable("OS_id")String  OS_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_OS controller started operation!");

		String service_return_msg = "";

		service_return_msg = OS_Activity_service.delete_os(OS_id);

		log.info("Object returned from delete_OS method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  OS noun from  database
	*
	*@return List of OS objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_OS", httpMethod = "GET",notes = "special search that gets all values of OS",response = OS.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_OS" ,headers="Accept=application/json")
    @ResponseBody
	public List<OS> get_all_OS() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_OS controller started operation!");

		List<OS> OS_list = new ArrayList<OS>();

		OS_list = OS_Activity_service.get_all_os();

		log.info("Object returned from get_all_OS method !");

 

        return OS_list;

	}




}