package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.ReasonForNotCount;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.ReasonForNotCountService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/ReasonForNotCount", description = "ReasonForNotCount of ReasonForNotCount",produces = "application/json")
@CrossOrigin
@Controller("ReasonForNotCountController")
@RequestMapping("/api/ReasonForNotCount")
public class ReasonForNotCountController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(ReasonForNotCountController.class.getName());

 


	private ReasonForNotCountService ReasonForNotCount_service;


	public ReasonForNotCountService get_ReasonForNotCount_service() {
		return ReasonForNotCount_service;
	}


	@Resource(name="ReasonForNotCountService")
	public void set_ReasonForNotCount_service(ReasonForNotCountService ReasonForNotCount_service) {
		this.ReasonForNotCount_service = ReasonForNotCount_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  ReasonForNotCount noun into database
	* @param the_ReasonForNotCount
	*@return ReasonForNotCount object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_ReasonForNotCount", httpMethod = "POST",notes = "creates a noun of ReasonForNotCount",response = ReasonForNotCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_ReasonForNotCount" ,headers="Accept=application/json")
    @ResponseBody
	public ReasonForNotCount create_ReasonForNotCount(@RequestBody ReasonForNotCount the_ReasonForNotCount) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_ReasonForNotCount controller started operation!");

		the_ReasonForNotCount.setId(null);

		ReasonForNotCount a_ReasonForNotCount = ReasonForNotCount_service.create_reasonfornotcount(the_ReasonForNotCount);

		log.info("Object returned from create_ReasonForNotCount method !");

 

        return a_ReasonForNotCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  ReasonForNotCount noun into database
	*@param the_ReasonForNotCount
	*@return ReasonForNotCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_ReasonForNotCount", httpMethod = "PUT",notes = "updates a noun of ReasonForNotCount",response = ReasonForNotCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_ReasonForNotCount" ,headers="Accept=application/json")
    @ResponseBody
	public ReasonForNotCount update_ReasonForNotCount(@RequestBody ReasonForNotCount the_ReasonForNotCount) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_ReasonForNotCount controller started operation!");

		ReasonForNotCount a_ReasonForNotCount;

		a_ReasonForNotCount = ReasonForNotCount_service.update_reasonfornotcount(the_ReasonForNotCount);

		log.info("Object returned from update_ReasonForNotCount method !");

 

        return a_ReasonForNotCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  ReasonForNotCount noun from  database based on given noun id
	*@param ReasonForNotCount_id
	*@return ReasonForNotCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_ReasonForNotCount/{ReasonForNotCount_id}", httpMethod = "GET",notes = "updates a noun of ReasonForNotCount",response = ReasonForNotCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_ReasonForNotCount/{ReasonForNotCount_id}" ,headers="Accept=application/json")
    @ResponseBody
	public ReasonForNotCount search_for_update_ReasonForNotCount(@PathVariable("ReasonForNotCount_id")String ReasonForNotCount_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_ReasonForNotCount controller started operation!");

		ReasonForNotCount the_ReasonForNotCount = new ReasonForNotCount();

		the_ReasonForNotCount = ReasonForNotCount_service.reasonfornotcount_search_for_update(ReasonForNotCount_id);

		log.info("Object returned from search_for_update_ReasonForNotCount method !");

 

        return the_ReasonForNotCount;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  ReasonForNotCount noun from  database based on given noun id
	*@param ReasonForNotCount_id
	*@return ReasonForNotCountobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_ReasonForNotCount/{ReasonForNotCount_id}", httpMethod = "DELETE",notes = "deletes a noun of ReasonForNotCount",response = ReasonForNotCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_ReasonForNotCount/{ReasonForNotCount_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_ReasonForNotCount(@PathVariable("ReasonForNotCount_id")String  ReasonForNotCount_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_ReasonForNotCount controller started operation!");

		String service_return_msg = "";

		service_return_msg = ReasonForNotCount_service.delete_reasonfornotcount(ReasonForNotCount_id);

		log.info("Object returned from delete_ReasonForNotCount method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  ReasonForNotCount noun from  database
	*
	*@return List of ReasonForNotCount objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_ReasonForNotCount", httpMethod = "GET",notes = "special search that gets all values of ReasonForNotCount",response = ReasonForNotCount.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_ReasonForNotCount" ,headers="Accept=application/json")
    @ResponseBody
	public List<ReasonForNotCount> get_all_ReasonForNotCount() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_ReasonForNotCount controller started operation!");

		List<ReasonForNotCount> ReasonForNotCount_list = new ArrayList<ReasonForNotCount>();

		ReasonForNotCount_list = ReasonForNotCount_service.get_all_reasonfornotcount();

		log.info("Object returned from get_all_ReasonForNotCount method !");

 

        return ReasonForNotCount_list;

	}




}