package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.UsedUs;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.UsedUs_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/UsedUs_Activity", description = "UsedUs_Activity of UsedUs_Activity",produces = "application/json")
@CrossOrigin
@Controller("UsedUs_ActivityController")
@RequestMapping("/api/UsedUs_Activity")
public class UsedUs_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(UsedUs_ActivityController.class.getName());

 


	private UsedUs_ActivityService UsedUs_Activity_service;


	public UsedUs_ActivityService get_UsedUs_Activity_service() {
		return UsedUs_Activity_service;
	}


	@Resource(name="UsedUs_ActivityService")
	public void set_UsedUs_Activity_service(UsedUs_ActivityService UsedUs_Activity_service) {
		this.UsedUs_Activity_service = UsedUs_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  UsedUs noun into database
	* @param the_UsedUs
	*@return UsedUs object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_UsedUs", httpMethod = "POST",notes = "creates a noun of UsedUs",response = UsedUs.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_UsedUs" ,headers="Accept=application/json")
    @ResponseBody
	public UsedUs create_UsedUs(@RequestBody UsedUs the_UsedUs) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_UsedUs controller started operation!");

		the_UsedUs.setId(null);

		UsedUs a_UsedUs = UsedUs_Activity_service.create_usedus(the_UsedUs);

		log.info("Object returned from create_UsedUs method !");

 

        return a_UsedUs;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  UsedUs noun into database
	*@param the_UsedUs
	*@return UsedUsobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_UsedUs", httpMethod = "PUT",notes = "updates a noun of UsedUs",response = UsedUs.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_UsedUs" ,headers="Accept=application/json")
    @ResponseBody
	public UsedUs update_UsedUs(@RequestBody UsedUs the_UsedUs) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_UsedUs controller started operation!");

		UsedUs a_UsedUs;

		a_UsedUs = UsedUs_Activity_service.update_usedus(the_UsedUs);

		log.info("Object returned from update_UsedUs method !");

 

        return a_UsedUs;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  UsedUs noun from  database based on given noun id
	*@param UsedUs_id
	*@return UsedUsobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_UsedUs/{UsedUs_id}", httpMethod = "GET",notes = "updates a noun of UsedUs",response = UsedUs.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_UsedUs/{UsedUs_id}" ,headers="Accept=application/json")
    @ResponseBody
	public UsedUs search_for_update_UsedUs(@PathVariable("UsedUs_id")String UsedUs_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_UsedUs controller started operation!");

		UsedUs the_UsedUs = new UsedUs();

		the_UsedUs = UsedUs_Activity_service.usedus_search_for_update(UsedUs_id);

		log.info("Object returned from search_for_update_UsedUs method !");

 

        return the_UsedUs;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  UsedUs noun from  database based on given noun id
	*@param UsedUs_id
	*@return UsedUsobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_UsedUs/{UsedUs_id}", httpMethod = "DELETE",notes = "deletes a noun of UsedUs",response = UsedUs.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_UsedUs/{UsedUs_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_UsedUs(@PathVariable("UsedUs_id")String  UsedUs_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_UsedUs controller started operation!");

		String service_return_msg = "";

		service_return_msg = UsedUs_Activity_service.delete_usedus(UsedUs_id);

		log.info("Object returned from delete_UsedUs method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  UsedUs noun from  database
	*
	*@return List of UsedUs objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_UsedUs", httpMethod = "GET",notes = "special search that gets all values of UsedUs",response = UsedUs.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_UsedUs" ,headers="Accept=application/json")
    @ResponseBody
	public List<UsedUs> get_all_UsedUs() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_UsedUs controller started operation!");

		List<UsedUs> UsedUs_list = new ArrayList<UsedUs>();

		UsedUs_list = UsedUs_Activity_service.get_all_usedus();

		log.info("Object returned from get_all_UsedUs method !");

 

        return UsedUs_list;

	}




}