package com.AssetRegisterBook.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.AssetRegisterBook.domain.core.WarrantyStatus;

import com.AssetRegisterBook.config.AssetRegisterBookSwaggerUIConstants;

import com.AssetRegisterBook.service.WarrantyStatus_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/api/WarrantyStatus_Activity", description = "WarrantyStatus_Activity of WarrantyStatus_Activity",produces = "application/json")
@CrossOrigin
@Controller("WarrantyStatus_ActivityController")
@RequestMapping("/api/WarrantyStatus_Activity")
public class WarrantyStatus_ActivityController  implements AssetRegisterBookSwaggerUIConstants {

private static Logger log = Logger.getLogger(WarrantyStatus_ActivityController.class.getName());

 


	private WarrantyStatus_ActivityService WarrantyStatus_Activity_service;


	public WarrantyStatus_ActivityService get_WarrantyStatus_Activity_service() {
		return WarrantyStatus_Activity_service;
	}


	@Resource(name="WarrantyStatus_ActivityService")
	public void set_WarrantyStatus_Activity_service(WarrantyStatus_ActivityService WarrantyStatus_Activity_service) {
		this.WarrantyStatus_Activity_service = WarrantyStatus_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  WarrantyStatus noun into database
	* @param the_WarrantyStatus
	*@return WarrantyStatus object will return for mongo
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_WarrantyStatus", httpMethod = "POST",notes = "creates a noun of WarrantyStatus",response = WarrantyStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_WarrantyStatus" ,headers="Accept=application/json")
    @ResponseBody
	public WarrantyStatus create_WarrantyStatus(@RequestBody WarrantyStatus the_WarrantyStatus) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_WarrantyStatus controller started operation!");

		the_WarrantyStatus.setId(null);

		WarrantyStatus a_WarrantyStatus = WarrantyStatus_Activity_service.create_warrantystatus(the_WarrantyStatus);

		log.info("Object returned from create_WarrantyStatus method !");

 

        return a_WarrantyStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  WarrantyStatus noun into database
	*@param the_WarrantyStatus
	*@return WarrantyStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_WarrantyStatus", httpMethod = "PUT",notes = "updates a noun of WarrantyStatus",response = WarrantyStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_WarrantyStatus" ,headers="Accept=application/json")
    @ResponseBody
	public WarrantyStatus update_WarrantyStatus(@RequestBody WarrantyStatus the_WarrantyStatus) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_WarrantyStatus controller started operation!");

		WarrantyStatus a_WarrantyStatus;

		a_WarrantyStatus = WarrantyStatus_Activity_service.update_warrantystatus(the_WarrantyStatus);

		log.info("Object returned from update_WarrantyStatus method !");

 

        return a_WarrantyStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  WarrantyStatus noun from  database based on given noun id
	*@param WarrantyStatus_id
	*@return WarrantyStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_WarrantyStatus/{WarrantyStatus_id}", httpMethod = "GET",notes = "updates a noun of WarrantyStatus",response = WarrantyStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_WarrantyStatus/{WarrantyStatus_id}" ,headers="Accept=application/json")
    @ResponseBody
	public WarrantyStatus search_for_update_WarrantyStatus(@PathVariable("WarrantyStatus_id")String WarrantyStatus_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_WarrantyStatus controller started operation!");

		WarrantyStatus the_WarrantyStatus = new WarrantyStatus();

		the_WarrantyStatus = WarrantyStatus_Activity_service.warrantystatus_search_for_update(WarrantyStatus_id);

		log.info("Object returned from search_for_update_WarrantyStatus method !");

 

        return the_WarrantyStatus;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  WarrantyStatus noun from  database based on given noun id
	*@param WarrantyStatus_id
	*@return WarrantyStatusobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_WarrantyStatus/{WarrantyStatus_id}", httpMethod = "DELETE",notes = "deletes a noun of WarrantyStatus",response = WarrantyStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_WarrantyStatus/{WarrantyStatus_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_WarrantyStatus(@PathVariable("WarrantyStatus_id")String  WarrantyStatus_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_WarrantyStatus controller started operation!");

		String service_return_msg = "";

		service_return_msg = WarrantyStatus_Activity_service.delete_warrantystatus(WarrantyStatus_id);

		log.info("Object returned from delete_WarrantyStatus method !");

 

        return service_return_msg;

	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  WarrantyStatus noun from  database
	*
	*@return List of WarrantyStatus objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_WarrantyStatus", httpMethod = "GET",notes = "special search that gets all values of WarrantyStatus",response = WarrantyStatus.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = AssetRegisterBookSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = AssetRegisterBookSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = AssetRegisterBookSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = AssetRegisterBookSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = AssetRegisterBookSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_WarrantyStatus" ,headers="Accept=application/json")
    @ResponseBody
	public List<WarrantyStatus> get_all_WarrantyStatus() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_WarrantyStatus controller started operation!");

		List<WarrantyStatus> WarrantyStatus_list = new ArrayList<WarrantyStatus>();

		WarrantyStatus_list = WarrantyStatus_Activity_service.get_all_warrantystatus();

		log.info("Object returned from get_all_WarrantyStatus method !");

 

        return WarrantyStatus_list;

	}




}