package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.arb;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("AssetregisterbookformDao")
public class AssetregisterbookformDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(AssetregisterbookformDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Assetregisterbookform noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Assetregisterbookform object will return
	*@throws Exception
	*/

	public arb assetregisterbookform_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("assetregisterbookform_search_for_update Dao started operation!");

		   arb  the_assetregisterbookform = couchbaseTemplate.findById(id,arb.class);
		  return the_assetregisterbookform;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Assetregisterbookform noun from  database
	*
	*
	*@return List of Assetregisterbookform object will return
	*@throws Exception
	*/

	public ArrayList<arb> get_all_assetregisterbookform() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_assetregisterbookform Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<arb>)  couchbaseTemplate.findByView("dev_arb","arb_by_name",query,arb.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Assetregisterbookform noun into database
	*@param Assetregisterbookform
	*@param user
	*@return Assetregisterbookform object will return
	*@throws Exception
	*/


	public arb create_assetregisterbookform(arb Assetregisterbookform ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_assetregisterbookform Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Assetregisterbookform.setid(clientKey);
 		 couchbaseTemplate.save(Assetregisterbookform);
 		 String viewName = "arb_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.arb\") {"//Assetregisterbookform
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_arb");//assetregisterbookform
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Assetregisterbookform;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Assetregisterbookform noun into database
	*@param Assetregisterbookform
	*@param user
	*@return the_Assetregisterbookform object will return
	*@throws Exception
	*/


	public arb update_assetregisterbookform(arb Assetregisterbookform) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_assetregisterbookform Dao started operation!");

 		 couchbaseTemplate.save(Assetregisterbookform);
		  return Assetregisterbookform;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Assetregisterbookform noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Assetregisterbookform id deleted based on id
	*@throws Exception
	*/


	public String  delete_assetregisterbookform(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_assetregisterbookform Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}