package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Category;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Category_ActivityDao")
public class Category_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Category_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Category noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Category object will return
	*@throws Exception
	*/

	public Category category_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("category_search_for_update Dao started operation!");

		   Category  the_category = couchbaseTemplate.findById(id,Category.class);
		  return the_category;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Category noun from  database
	*
	*
	*@return List of Category object will return
	*@throws Exception
	*/

	public ArrayList<Category> get_all_category() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_category Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Category>)  couchbaseTemplate.findByView("dev_category","category_by_name",query,Category.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Category noun into database
	*@param Category
	*@param user
	*@return Category object will return
	*@throws Exception
	*/


	public Category create_category(Category Category ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_category Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Category.setId(clientKey);
 		 couchbaseTemplate.save(Category);
 		 String viewName = "category_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Category\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_category");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Category;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Category noun into database
	*@param Category
	*@param user
	*@return the_Category object will return
	*@throws Exception
	*/


	public Category update_category(Category Category) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_category Dao started operation!");

 		 couchbaseTemplate.save(Category);
		  return Category;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Category noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Category id deleted based on id
	*@throws Exception
	*/


	public String  delete_category(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_category Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}