package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Currency;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Currency_ActivityDao")
public class Currency_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Currency_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Currency noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Currency object will return
	*@throws Exception
	*/

	public Currency currency_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("currency_search_for_update Dao started operation!");

		   Currency  the_currency = couchbaseTemplate.findById(id,Currency.class);
		  return the_currency;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Currency noun from  database
	*
	*
	*@return List of Currency object will return
	*@throws Exception
	*/

	public ArrayList<Currency> get_all_currency() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_currency Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Currency>)  couchbaseTemplate.findByView("dev_currency","currency_by_name",query,Currency.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Currency noun into database
	*@param Currency
	*@param user
	*@return Currency object will return
	*@throws Exception
	*/


	public Currency create_currency(Currency Currency ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_currency Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Currency.setId(clientKey);
 		 couchbaseTemplate.save(Currency);
 		 String viewName = "currency_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Currency\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_currency");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Currency;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Currency noun into database
	*@param Currency
	*@param user
	*@return the_Currency object will return
	*@throws Exception
	*/


	public Currency update_currency(Currency Currency) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_currency Dao started operation!");

 		 couchbaseTemplate.save(Currency);
		  return Currency;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Currency noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Currency id deleted based on id
	*@throws Exception
	*/


	public String  delete_currency(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_currency Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}