package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.CurrentLocation;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("CurrentLocation_Default_ActivityDao")
public class CurrentLocation_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(CurrentLocation_Default_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  CurrentLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_CurrentLocation object will return
	*@throws Exception
	*/

	public CurrentLocation currentlocation_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("currentlocation_search_for_update Dao started operation!");

		   CurrentLocation  the_currentlocation = couchbaseTemplate.findById(id,CurrentLocation.class);
		  return the_currentlocation;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  CurrentLocation noun from  database
	*
	*
	*@return List of CurrentLocation object will return
	*@throws Exception
	*/

	public ArrayList<CurrentLocation> get_all_currentlocation() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_currentlocation Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<CurrentLocation>)  couchbaseTemplate.findByView("dev_currentlocation","currentlocation_by_name",query,CurrentLocation.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  CurrentLocation noun into database
	*@param CurrentLocation
	*@param user
	*@return CurrentLocation object will return
	*@throws Exception
	*/


	public CurrentLocation create_currentlocation(CurrentLocation CurrentLocation ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_currentlocation Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 CurrentLocation.setid(clientKey);
 		 couchbaseTemplate.save(CurrentLocation);
 		 String viewName = "currentlocation_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.CurrentLocation\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_currentlocation");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return CurrentLocation;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  CurrentLocation noun into database
	*@param CurrentLocation
	*@param user
	*@return the_CurrentLocation object will return
	*@throws Exception
	*/


	public CurrentLocation update_currentlocation(CurrentLocation CurrentLocation) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_currentlocation Dao started operation!");

 		 couchbaseTemplate.save(CurrentLocation);
		  return CurrentLocation;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  CurrentLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_CurrentLocation id deleted based on id
	*@throws Exception
	*/


	public String  delete_currentlocation(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_currentlocation Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}