package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.OfficeLocation;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("OfficeLocation_ActivityDao")
public class OfficeLocation_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(OfficeLocation_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  OfficeLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_OfficeLocation object will return
	*@throws Exception
	*/

	public OfficeLocation officelocation_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("officelocation_search_for_update Dao started operation!");

		   OfficeLocation  the_officelocation = couchbaseTemplate.findById(id,OfficeLocation.class);
		  return the_officelocation;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  OfficeLocation noun from  database
	*
	*
	*@return List of OfficeLocation object will return
	*@throws Exception
	*/

	public ArrayList<OfficeLocation> get_all_officelocation() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_officelocation Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<OfficeLocation>)  couchbaseTemplate.findByView("dev_officelocation","officelocation_by_name",query,OfficeLocation.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  OfficeLocation noun into database
	*@param OfficeLocation
	*@param user
	*@return OfficeLocation object will return
	*@throws Exception
	*/


	public OfficeLocation create_officelocation(OfficeLocation OfficeLocation ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_officelocation Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 OfficeLocation.setid(clientKey);
 		 couchbaseTemplate.save(OfficeLocation);
 		 String viewName = "officelocation_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.OfficeLocation\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_officelocation");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return OfficeLocation;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  OfficeLocation noun into database
	*@param OfficeLocation
	*@param user
	*@return the_OfficeLocation object will return
	*@throws Exception
	*/


	public OfficeLocation update_officelocation(OfficeLocation OfficeLocation) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_officelocation Dao started operation!");

 		 couchbaseTemplate.save(OfficeLocation);
		  return OfficeLocation;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  OfficeLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_OfficeLocation id deleted based on id
	*@throws Exception
	*/


	public String  delete_officelocation(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_officelocation Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}