package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Poyear;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Poyear_ActivityDao")
public class Poyear_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Poyear_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Poyear noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poyear object will return
	*@throws Exception
	*/

	public Poyear poyear_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("poyear_search_for_update Dao started operation!");

		   Poyear  the_poyear = couchbaseTemplate.findById(id,Poyear.class);
		  return the_poyear;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Poyear noun from  database
	*
	*
	*@return List of Poyear object will return
	*@throws Exception
	*/

	public ArrayList<Poyear> get_all_poyear() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_poyear Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Poyear>)  couchbaseTemplate.findByView("dev_poyear","poyear_by_name",query,Poyear.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Poyear noun into database
	*@param Poyear
	*@param user
	*@return Poyear object will return
	*@throws Exception
	*/


	public Poyear create_poyear(Poyear Poyear ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_poyear Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Poyear.setId(clientKey);
 		 couchbaseTemplate.save(Poyear);
 		 String viewName = "poyear_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Poyear\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_poyear");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Poyear;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Poyear noun into database
	*@param Poyear
	*@param user
	*@return the_Poyear object will return
	*@throws Exception
	*/


	public Poyear update_poyear(Poyear Poyear) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_poyear Dao started operation!");

 		 couchbaseTemplate.save(Poyear);
		  return Poyear;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Poyear noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poyear id deleted based on id
	*@throws Exception
	*/


	public String  delete_poyear(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_poyear Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}