package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Purpose;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Purpose_ActivityDao")
public class Purpose_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Purpose_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Purpose noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Purpose object will return
	*@throws Exception
	*/

	public Purpose purpose_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("purpose_search_for_update Dao started operation!");

		   Purpose  the_purpose = couchbaseTemplate.findById(id,Purpose.class);
		  return the_purpose;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Purpose noun from  database
	*
	*
	*@return List of Purpose object will return
	*@throws Exception
	*/

	public ArrayList<Purpose> get_all_purpose() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_purpose Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Purpose>)  couchbaseTemplate.findByView("dev_purpose","purpose_by_name",query,Purpose.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Purpose noun into database
	*@param Purpose
	*@param user
	*@return Purpose object will return
	*@throws Exception
	*/


	public Purpose create_purpose(Purpose Purpose ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_purpose Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Purpose.setid(clientKey);
 		 couchbaseTemplate.save(Purpose);
 		 String viewName = "purpose_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Purpose\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_purpose");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Purpose;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Purpose noun into database
	*@param Purpose
	*@param user
	*@return the_Purpose object will return
	*@throws Exception
	*/


	public Purpose update_purpose(Purpose Purpose) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_purpose Dao started operation!");

 		 couchbaseTemplate.save(Purpose);
		  return Purpose;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Purpose noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Purpose id deleted based on id
	*@throws Exception
	*/


	public String  delete_purpose(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_purpose Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}