package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Room;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Room_Default_ActivityDao")
public class Room_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Room_Default_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Room noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Room object will return
	*@throws Exception
	*/

	public Room room_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("room_search_for_update Dao started operation!");

		   Room  the_room = couchbaseTemplate.findById(id,Room.class);
		  return the_room;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Room noun from  database
	*
	*
	*@return List of Room object will return
	*@throws Exception
	*/

	public ArrayList<Room> get_all_room() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_room Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Room>)  couchbaseTemplate.findByView("dev_room","room_by_name",query,Room.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Room noun into database
	*@param Room
	*@param user
	*@return Room object will return
	*@throws Exception
	*/


	public Room create_room(Room Room ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_room Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Room.setid(clientKey);
 		 couchbaseTemplate.save(Room);
 		 String viewName = "room_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Room\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_room");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Room;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Room noun into database
	*@param Room
	*@param user
	*@return the_Room object will return
	*@throws Exception
	*/


	public Room update_room(Room Room) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_room Dao started operation!");

 		 couchbaseTemplate.save(Room);
		  return Room;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Room noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Room id deleted based on id
	*@throws Exception
	*/


	public String  delete_room(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_room Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}