package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Sg;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Sg_ActivityDao")
public class Sg_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Sg_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Sg noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Sg object will return
	*@throws Exception
	*/

	public Sg sg_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("sg_search_for_update Dao started operation!");

		   Sg  the_sg = couchbaseTemplate.findById(id,Sg.class);
		  return the_sg;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Sg noun from  database
	*
	*
	*@return List of Sg object will return
	*@throws Exception
	*/

	public ArrayList<Sg> get_all_sg() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_sg Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Sg>)  couchbaseTemplate.findByView("dev_sg","sg_by_name",query,Sg.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Sg noun into database
	*@param Sg
	*@param user
	*@return Sg object will return
	*@throws Exception
	*/


	public Sg create_sg(Sg Sg ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_sg Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Sg.setId(clientKey);
 		 couchbaseTemplate.save(Sg);
 		 String viewName = "sg_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Sg\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_sg");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Sg;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Sg noun into database
	*@param Sg
	*@param user
	*@return the_Sg object will return
	*@throws Exception
	*/


	public Sg update_sg(Sg Sg) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_sg Dao started operation!");

 		 couchbaseTemplate.save(Sg);
		  return Sg;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Sg noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Sg id deleted based on id
	*@throws Exception
	*/


	public String  delete_sg(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_sg Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}