package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Type;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Type_ActivityDao")
public class Type_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Type_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Type noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Type object will return
	*@throws Exception
	*/

	public Type type_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("type_search_for_update Dao started operation!");

		   Type  the_type = couchbaseTemplate.findById(id,Type.class);
		  return the_type;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Type noun from  database
	*
	*
	*@return List of Type object will return
	*@throws Exception
	*/

	public ArrayList<Type> get_all_type() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_type Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Type>)  couchbaseTemplate.findByView("dev_type","type_by_name",query,Type.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Type noun into database
	*@param Type
	*@param user
	*@return Type object will return
	*@throws Exception
	*/


	public Type create_type(Type Type ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_type Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Type.setid(clientKey);
 		 couchbaseTemplate.save(Type);
 		 String viewName = "type_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Type\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_type");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Type;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Type noun into database
	*@param Type
	*@param user
	*@return the_Type object will return
	*@throws Exception
	*/


	public Type update_type(Type Type) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_type Dao started operation!");

 		 couchbaseTemplate.save(Type);
		  return Type;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Type noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Type id deleted based on id
	*@throws Exception
	*/


	public String  delete_type(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_type Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}