package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.UserAllocationStatus;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("UserAllocationStatus_ActivityDao")
public class UserAllocationStatus_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(UserAllocationStatus_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  UserAllocationStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_UserAllocationStatus object will return
	*@throws Exception
	*/

	public UserAllocationStatus userallocationstatus_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("userallocationstatus_search_for_update Dao started operation!");

		   UserAllocationStatus  the_userallocationstatus = couchbaseTemplate.findById(id,UserAllocationStatus.class);
		  return the_userallocationstatus;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  UserAllocationStatus noun from  database
	*
	*
	*@return List of UserAllocationStatus object will return
	*@throws Exception
	*/

	public ArrayList<UserAllocationStatus> get_all_userallocationstatus() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_userallocationstatus Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<UserAllocationStatus>)  couchbaseTemplate.findByView("dev_userallocationstatus","userallocationstatus_by_name",query,UserAllocationStatus.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  UserAllocationStatus noun into database
	*@param UserAllocationStatus
	*@param user
	*@return UserAllocationStatus object will return
	*@throws Exception
	*/


	public UserAllocationStatus create_userallocationstatus(UserAllocationStatus UserAllocationStatus ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_userallocationstatus Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 UserAllocationStatus.setId(clientKey);
 		 couchbaseTemplate.save(UserAllocationStatus);
 		 String viewName = "userallocationstatus_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.UserAllocationStatus\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_userallocationstatus");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return UserAllocationStatus;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  UserAllocationStatus noun into database
	*@param UserAllocationStatus
	*@param user
	*@return the_UserAllocationStatus object will return
	*@throws Exception
	*/


	public UserAllocationStatus update_userallocationstatus(UserAllocationStatus UserAllocationStatus) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_userallocationstatus Dao started operation!");

 		 couchbaseTemplate.save(UserAllocationStatus);
		  return UserAllocationStatus;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  UserAllocationStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_UserAllocationStatus id deleted based on id
	*@throws Exception
	*/


	public String  delete_userallocationstatus(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_userallocationstatus Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}