package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.WarrantyStatus;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("WarrantyStatus_ActivityDao")
public class WarrantyStatus_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(WarrantyStatus_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  WarrantyStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_WarrantyStatus object will return
	*@throws Exception
	*/

	public WarrantyStatus warrantystatus_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("warrantystatus_search_for_update Dao started operation!");

		   WarrantyStatus  the_warrantystatus = couchbaseTemplate.findById(id,WarrantyStatus.class);
		  return the_warrantystatus;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  WarrantyStatus noun from  database
	*
	*
	*@return List of WarrantyStatus object will return
	*@throws Exception
	*/

	public ArrayList<WarrantyStatus> get_all_warrantystatus() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_warrantystatus Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<WarrantyStatus>)  couchbaseTemplate.findByView("dev_warrantystatus","warrantystatus_by_name",query,WarrantyStatus.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  WarrantyStatus noun into database
	*@param WarrantyStatus
	*@param user
	*@return WarrantyStatus object will return
	*@throws Exception
	*/


	public WarrantyStatus create_warrantystatus(WarrantyStatus WarrantyStatus ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_warrantystatus Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 WarrantyStatus.setId(clientKey);
 		 couchbaseTemplate.save(WarrantyStatus);
 		 String viewName = "warrantystatus_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.WarrantyStatus\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_warrantystatus");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return WarrantyStatus;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  WarrantyStatus noun into database
	*@param WarrantyStatus
	*@param user
	*@return the_WarrantyStatus object will return
	*@throws Exception
	*/


	public WarrantyStatus update_warrantystatus(WarrantyStatus WarrantyStatus) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_warrantystatus Dao started operation!");

 		 couchbaseTemplate.save(WarrantyStatus);
		  return WarrantyStatus;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  WarrantyStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_WarrantyStatus id deleted based on id
	*@throws Exception
	*/


	public String  delete_warrantystatus(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_warrantystatus Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}