package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.BillingEntity;

import com.AssetRegisterBook.dao.couchbase.BillingEntity_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("BillingEntity_ActivityService")
public class BillingEntity_ActivityService   {
private static Logger log = Logger.getLogger(BillingEntity_ActivityService.class.getName());

	private BillingEntity_ActivityDao BillingEntity_Activity_dao;


	public BillingEntity_ActivityDao get_BillingEntity_Activity_dao() {
		return BillingEntity_Activity_dao;
	}


	@Resource(name="BillingEntity_ActivityDao")
	public void set_BillingEntity_Activity_dao(BillingEntity_ActivityDao BillingEntity_Activity_dao) {
		this.BillingEntity_Activity_dao = BillingEntity_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  BillingEntity noun into database
	*@param BillingEntity
	*@param user
	*@return the_BillingEntity object will return
	*@throws Exception
	*/

	public BillingEntity create_billingentity(BillingEntity BillingEntity) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_billingentity service operation started !");

		try{
			BillingEntity the_BillingEntity;

			the_BillingEntity = BillingEntity_Activity_dao.create_billingentity(BillingEntity);

 			log.info(" Object returned from create_billingentity  service method !");
			return the_BillingEntity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_billingentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  BillingEntity noun into database
	*@param BillingEntity
	*@param user
	*@return the_BillingEntity object will return
	*@throws Exception
	*/

	public BillingEntity update_billingentity(BillingEntity BillingEntity) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_billingentity service operation started !");

		try{
			BillingEntity the_BillingEntity;

			the_BillingEntity = BillingEntity_Activity_dao.update_billingentity(BillingEntity);

 			log.info(" Object returned from update_billingentity  service method !");
			return the_BillingEntity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_billingentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  BillingEntity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_BillingEntity object will return
	*@throws Exception
	*/

	public BillingEntity billingentity_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("billingentity_search_for_update service operation started !");

		try{
			BillingEntity the_BillingEntity;

			the_BillingEntity = BillingEntity_Activity_dao.billingentity_search_for_update(id);

 			log.info(" Object returned from billingentity_search_for_update  service method !");
			return the_BillingEntity;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("billingentity_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  BillingEntity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_BillingEntity id deleted based on id
	*@throws Exception
	*/

	public String  delete_billingentity(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_billingentity service operation started !");

		try{
			String method_return_message;

			method_return_message = BillingEntity_Activity_dao.delete_billingentity(id);

 			log.info(" Object returned from delete_billingentity  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_billingentity service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  BillingEntity noun from  database
	*
	*
	*@return List of BillingEntity object will return
	*@throws Exception
	*/

	public ArrayList<BillingEntity> get_all_billingentity() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<BillingEntity> BillingEntity_list;

			BillingEntity_list = BillingEntity_Activity_dao.get_all_billingentity();

 			log.info(" Object returned from   service method !");
			return BillingEntity_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}