package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.CurrentLocation;

import com.AssetRegisterBook.dao.couchbase.CurrentLocation_Default_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("CurrentLocation_Default_ActivityService")
public class CurrentLocation_Default_ActivityService   {
private static Logger log = Logger.getLogger(CurrentLocation_Default_ActivityService.class.getName());

	private CurrentLocation_Default_ActivityDao CurrentLocation_Default_Activity_dao;


	public CurrentLocation_Default_ActivityDao get_CurrentLocation_Default_Activity_dao() {
		return CurrentLocation_Default_Activity_dao;
	}


	@Resource(name="CurrentLocation_Default_ActivityDao")
	public void set_CurrentLocation_Default_Activity_dao(CurrentLocation_Default_ActivityDao CurrentLocation_Default_Activity_dao) {
		this.CurrentLocation_Default_Activity_dao = CurrentLocation_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  CurrentLocation noun into database
	*@param CurrentLocation
	*@param user
	*@return the_CurrentLocation object will return
	*@throws Exception
	*/

	public CurrentLocation create_currentlocation(CurrentLocation CurrentLocation) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_currentlocation service operation started !");

		try{
			CurrentLocation the_CurrentLocation;

			the_CurrentLocation = CurrentLocation_Default_Activity_dao.create_currentlocation(CurrentLocation);

 			log.info(" Object returned from create_currentlocation  service method !");
			return the_CurrentLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_currentlocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  CurrentLocation noun into database
	*@param CurrentLocation
	*@param user
	*@return the_CurrentLocation object will return
	*@throws Exception
	*/

	public CurrentLocation update_currentlocation(CurrentLocation CurrentLocation) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_currentlocation service operation started !");

		try{
			CurrentLocation the_CurrentLocation;

			the_CurrentLocation = CurrentLocation_Default_Activity_dao.update_currentlocation(CurrentLocation);

 			log.info(" Object returned from update_currentlocation  service method !");
			return the_CurrentLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_currentlocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  CurrentLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_CurrentLocation object will return
	*@throws Exception
	*/

	public CurrentLocation currentlocation_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("currentlocation_search_for_update service operation started !");

		try{
			CurrentLocation the_CurrentLocation;

			the_CurrentLocation = CurrentLocation_Default_Activity_dao.currentlocation_search_for_update(id);

 			log.info(" Object returned from currentlocation_search_for_update  service method !");
			return the_CurrentLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("currentlocation_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  CurrentLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_CurrentLocation id deleted based on id
	*@throws Exception
	*/

	public String  delete_currentlocation(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_currentlocation service operation started !");

		try{
			String method_return_message;

			method_return_message = CurrentLocation_Default_Activity_dao.delete_currentlocation(id);

 			log.info(" Object returned from delete_currentlocation  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_currentlocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  CurrentLocation noun from  database
	*
	*
	*@return List of CurrentLocation object will return
	*@throws Exception
	*/

	public ArrayList<CurrentLocation> get_all_currentlocation() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<CurrentLocation> CurrentLocation_list;

			CurrentLocation_list = CurrentLocation_Default_Activity_dao.get_all_currentlocation();

 			log.info(" Object returned from   service method !");
			return CurrentLocation_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}