package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.OfficeLocation;

import com.AssetRegisterBook.dao.couchbase.OfficeLocation_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("OfficeLocation_ActivityService")
public class OfficeLocation_ActivityService   {
private static Logger log = Logger.getLogger(OfficeLocation_ActivityService.class.getName());

	private OfficeLocation_ActivityDao OfficeLocation_Activity_dao;


	public OfficeLocation_ActivityDao get_OfficeLocation_Activity_dao() {
		return OfficeLocation_Activity_dao;
	}


	@Resource(name="OfficeLocation_ActivityDao")
	public void set_OfficeLocation_Activity_dao(OfficeLocation_ActivityDao OfficeLocation_Activity_dao) {
		this.OfficeLocation_Activity_dao = OfficeLocation_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  OfficeLocation noun into database
	*@param OfficeLocation
	*@param user
	*@return the_OfficeLocation object will return
	*@throws Exception
	*/

	public OfficeLocation create_officelocation(OfficeLocation OfficeLocation) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_officelocation service operation started !");

		try{
			OfficeLocation the_OfficeLocation;

			the_OfficeLocation = OfficeLocation_Activity_dao.create_officelocation(OfficeLocation);

 			log.info(" Object returned from create_officelocation  service method !");
			return the_OfficeLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_officelocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  OfficeLocation noun into database
	*@param OfficeLocation
	*@param user
	*@return the_OfficeLocation object will return
	*@throws Exception
	*/

	public OfficeLocation update_officelocation(OfficeLocation OfficeLocation) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_officelocation service operation started !");

		try{
			OfficeLocation the_OfficeLocation;

			the_OfficeLocation = OfficeLocation_Activity_dao.update_officelocation(OfficeLocation);

 			log.info(" Object returned from update_officelocation  service method !");
			return the_OfficeLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_officelocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  OfficeLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_OfficeLocation object will return
	*@throws Exception
	*/

	public OfficeLocation officelocation_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("officelocation_search_for_update service operation started !");

		try{
			OfficeLocation the_OfficeLocation;

			the_OfficeLocation = OfficeLocation_Activity_dao.officelocation_search_for_update(id);

 			log.info(" Object returned from officelocation_search_for_update  service method !");
			return the_OfficeLocation;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("officelocation_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  OfficeLocation noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_OfficeLocation id deleted based on id
	*@throws Exception
	*/

	public String  delete_officelocation(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_officelocation service operation started !");

		try{
			String method_return_message;

			method_return_message = OfficeLocation_Activity_dao.delete_officelocation(id);

 			log.info(" Object returned from delete_officelocation  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_officelocation service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  OfficeLocation noun from  database
	*
	*
	*@return List of OfficeLocation object will return
	*@throws Exception
	*/

	public ArrayList<OfficeLocation> get_all_officelocation() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<OfficeLocation> OfficeLocation_list;

			OfficeLocation_list = OfficeLocation_Activity_dao.get_all_officelocation();

 			log.info(" Object returned from   service method !");
			return OfficeLocation_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}