package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.Poyear;

import com.AssetRegisterBook.dao.couchbase.Poyear_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Poyear_ActivityService")
public class Poyear_ActivityService   {
private static Logger log = Logger.getLogger(Poyear_ActivityService.class.getName());

	private Poyear_ActivityDao Poyear_Activity_dao;


	public Poyear_ActivityDao get_Poyear_Activity_dao() {
		return Poyear_Activity_dao;
	}


	@Resource(name="Poyear_ActivityDao")
	public void set_Poyear_Activity_dao(Poyear_ActivityDao Poyear_Activity_dao) {
		this.Poyear_Activity_dao = Poyear_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Poyear noun into database
	*@param Poyear
	*@param user
	*@return the_Poyear object will return
	*@throws Exception
	*/

	public Poyear create_poyear(Poyear Poyear) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_poyear service operation started !");

		try{
			Poyear the_Poyear;

			the_Poyear = Poyear_Activity_dao.create_poyear(Poyear);

 			log.info(" Object returned from create_poyear  service method !");
			return the_Poyear;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_poyear service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Poyear noun into database
	*@param Poyear
	*@param user
	*@return the_Poyear object will return
	*@throws Exception
	*/

	public Poyear update_poyear(Poyear Poyear) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_poyear service operation started !");

		try{
			Poyear the_Poyear;

			the_Poyear = Poyear_Activity_dao.update_poyear(Poyear);

 			log.info(" Object returned from update_poyear  service method !");
			return the_Poyear;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_poyear service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Poyear noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poyear object will return
	*@throws Exception
	*/

	public Poyear poyear_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("poyear_search_for_update service operation started !");

		try{
			Poyear the_Poyear;

			the_Poyear = Poyear_Activity_dao.poyear_search_for_update(id);

 			log.info(" Object returned from poyear_search_for_update  service method !");
			return the_Poyear;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("poyear_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Poyear noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Poyear id deleted based on id
	*@throws Exception
	*/

	public String  delete_poyear(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_poyear service operation started !");

		try{
			String method_return_message;

			method_return_message = Poyear_Activity_dao.delete_poyear(id);

 			log.info(" Object returned from delete_poyear  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_poyear service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Poyear noun from  database
	*
	*
	*@return List of Poyear object will return
	*@throws Exception
	*/

	public ArrayList<Poyear> get_all_poyear() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Poyear> Poyear_list;

			Poyear_list = Poyear_Activity_dao.get_all_poyear();

 			log.info(" Object returned from   service method !");
			return Poyear_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}