package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.Room;

import com.AssetRegisterBook.dao.couchbase.Room_Default_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Room_Default_ActivityService")
public class Room_Default_ActivityService   {
private static Logger log = Logger.getLogger(Room_Default_ActivityService.class.getName());

	private Room_Default_ActivityDao Room_Default_Activity_dao;


	public Room_Default_ActivityDao get_Room_Default_Activity_dao() {
		return Room_Default_Activity_dao;
	}


	@Resource(name="Room_Default_ActivityDao")
	public void set_Room_Default_Activity_dao(Room_Default_ActivityDao Room_Default_Activity_dao) {
		this.Room_Default_Activity_dao = Room_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Room noun into database
	*@param Room
	*@param user
	*@return the_Room object will return
	*@throws Exception
	*/

	public Room create_room(Room Room) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_room service operation started !");

		try{
			Room the_Room;

			the_Room = Room_Default_Activity_dao.create_room(Room);

 			log.info(" Object returned from create_room  service method !");
			return the_Room;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_room service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Room noun into database
	*@param Room
	*@param user
	*@return the_Room object will return
	*@throws Exception
	*/

	public Room update_room(Room Room) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_room service operation started !");

		try{
			Room the_Room;

			the_Room = Room_Default_Activity_dao.update_room(Room);

 			log.info(" Object returned from update_room  service method !");
			return the_Room;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_room service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Room noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Room object will return
	*@throws Exception
	*/

	public Room room_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("room_search_for_update service operation started !");

		try{
			Room the_Room;

			the_Room = Room_Default_Activity_dao.room_search_for_update(id);

 			log.info(" Object returned from room_search_for_update  service method !");
			return the_Room;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("room_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Room noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Room id deleted based on id
	*@throws Exception
	*/

	public String  delete_room(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_room service operation started !");

		try{
			String method_return_message;

			method_return_message = Room_Default_Activity_dao.delete_room(id);

 			log.info(" Object returned from delete_room  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_room service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Room noun from  database
	*
	*
	*@return List of Room object will return
	*@throws Exception
	*/

	public ArrayList<Room> get_all_room() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Room> Room_list;

			Room_list = Room_Default_Activity_dao.get_all_room();

 			log.info(" Object returned from   service method !");
			return Room_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}