package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.UserAllocationStatus;

import com.AssetRegisterBook.dao.couchbase.UserAllocationStatus_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("UserAllocationStatus_ActivityService")
public class UserAllocationStatus_ActivityService   {
private static Logger log = Logger.getLogger(UserAllocationStatus_ActivityService.class.getName());

	private UserAllocationStatus_ActivityDao UserAllocationStatus_Activity_dao;


	public UserAllocationStatus_ActivityDao get_UserAllocationStatus_Activity_dao() {
		return UserAllocationStatus_Activity_dao;
	}


	@Resource(name="UserAllocationStatus_ActivityDao")
	public void set_UserAllocationStatus_Activity_dao(UserAllocationStatus_ActivityDao UserAllocationStatus_Activity_dao) {
		this.UserAllocationStatus_Activity_dao = UserAllocationStatus_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  UserAllocationStatus noun into database
	*@param UserAllocationStatus
	*@param user
	*@return the_UserAllocationStatus object will return
	*@throws Exception
	*/

	public UserAllocationStatus create_userallocationstatus(UserAllocationStatus UserAllocationStatus) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_userallocationstatus service operation started !");

		try{
			UserAllocationStatus the_UserAllocationStatus;

			the_UserAllocationStatus = UserAllocationStatus_Activity_dao.create_userallocationstatus(UserAllocationStatus);

 			log.info(" Object returned from create_userallocationstatus  service method !");
			return the_UserAllocationStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_userallocationstatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  UserAllocationStatus noun into database
	*@param UserAllocationStatus
	*@param user
	*@return the_UserAllocationStatus object will return
	*@throws Exception
	*/

	public UserAllocationStatus update_userallocationstatus(UserAllocationStatus UserAllocationStatus) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_userallocationstatus service operation started !");

		try{
			UserAllocationStatus the_UserAllocationStatus;

			the_UserAllocationStatus = UserAllocationStatus_Activity_dao.update_userallocationstatus(UserAllocationStatus);

 			log.info(" Object returned from update_userallocationstatus  service method !");
			return the_UserAllocationStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_userallocationstatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  UserAllocationStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_UserAllocationStatus object will return
	*@throws Exception
	*/

	public UserAllocationStatus userallocationstatus_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("userallocationstatus_search_for_update service operation started !");

		try{
			UserAllocationStatus the_UserAllocationStatus;

			the_UserAllocationStatus = UserAllocationStatus_Activity_dao.userallocationstatus_search_for_update(id);

 			log.info(" Object returned from userallocationstatus_search_for_update  service method !");
			return the_UserAllocationStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("userallocationstatus_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  UserAllocationStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_UserAllocationStatus id deleted based on id
	*@throws Exception
	*/

	public String  delete_userallocationstatus(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_userallocationstatus service operation started !");

		try{
			String method_return_message;

			method_return_message = UserAllocationStatus_Activity_dao.delete_userallocationstatus(id);

 			log.info(" Object returned from delete_userallocationstatus  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_userallocationstatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  UserAllocationStatus noun from  database
	*
	*
	*@return List of UserAllocationStatus object will return
	*@throws Exception
	*/

	public ArrayList<UserAllocationStatus> get_all_userallocationstatus() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<UserAllocationStatus> UserAllocationStatus_list;

			UserAllocationStatus_list = UserAllocationStatus_Activity_dao.get_all_userallocationstatus();

 			log.info(" Object returned from   service method !");
			return UserAllocationStatus_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}