package com.AssetRegisterBook.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.AssetRegisterBook.domain.core.WarrantyStatus;

import com.AssetRegisterBook.dao.couchbase.WarrantyStatus_ActivityDao;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("WarrantyStatus_ActivityService")
public class WarrantyStatus_ActivityService   {
private static Logger log = Logger.getLogger(WarrantyStatus_ActivityService.class.getName());

	private WarrantyStatus_ActivityDao WarrantyStatus_Activity_dao;


	public WarrantyStatus_ActivityDao get_WarrantyStatus_Activity_dao() {
		return WarrantyStatus_Activity_dao;
	}


	@Resource(name="WarrantyStatus_ActivityDao")
	public void set_WarrantyStatus_Activity_dao(WarrantyStatus_ActivityDao WarrantyStatus_Activity_dao) {
		this.WarrantyStatus_Activity_dao = WarrantyStatus_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  WarrantyStatus noun into database
	*@param WarrantyStatus
	*@param user
	*@return the_WarrantyStatus object will return
	*@throws Exception
	*/

	public WarrantyStatus create_warrantystatus(WarrantyStatus WarrantyStatus) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_warrantystatus service operation started !");

		try{
			WarrantyStatus the_WarrantyStatus;

			the_WarrantyStatus = WarrantyStatus_Activity_dao.create_warrantystatus(WarrantyStatus);

 			log.info(" Object returned from create_warrantystatus  service method !");
			return the_WarrantyStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_warrantystatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  WarrantyStatus noun into database
	*@param WarrantyStatus
	*@param user
	*@return the_WarrantyStatus object will return
	*@throws Exception
	*/

	public WarrantyStatus update_warrantystatus(WarrantyStatus WarrantyStatus) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_warrantystatus service operation started !");

		try{
			WarrantyStatus the_WarrantyStatus;

			the_WarrantyStatus = WarrantyStatus_Activity_dao.update_warrantystatus(WarrantyStatus);

 			log.info(" Object returned from update_warrantystatus  service method !");
			return the_WarrantyStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_warrantystatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  WarrantyStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_WarrantyStatus object will return
	*@throws Exception
	*/

	public WarrantyStatus warrantystatus_search_for_update(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("warrantystatus_search_for_update service operation started !");

		try{
			WarrantyStatus the_WarrantyStatus;

			the_WarrantyStatus = WarrantyStatus_Activity_dao.warrantystatus_search_for_update(id);

 			log.info(" Object returned from warrantystatus_search_for_update  service method !");
			return the_WarrantyStatus;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("warrantystatus_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  WarrantyStatus noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_WarrantyStatus id deleted based on id
	*@throws Exception
	*/

	public String  delete_warrantystatus(String id ) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_warrantystatus service operation started !");

		try{
			String method_return_message;

			method_return_message = WarrantyStatus_Activity_dao.delete_warrantystatus(id);

 			log.info(" Object returned from delete_warrantystatus  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_warrantystatus service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  WarrantyStatus noun from  database
	*
	*
	*@return List of WarrantyStatus object will return
	*@throws Exception
	*/

	public ArrayList<WarrantyStatus> get_all_warrantystatus() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<WarrantyStatus> WarrantyStatus_list;

			WarrantyStatus_list = WarrantyStatus_Activity_dao.get_all_warrantystatus();

 			log.info(" Object returned from   service method !");
			return WarrantyStatus_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}