package com.AssetRegisterBook.domain.core;

import org.springframework.data.annotation.Id;

import org.springframework.data.couchbase.core.mapping.Document;

import org.springframework.data.annotation.TypeAlias;

import org.springframework.data.couchbase.core.mapping.Field;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonProperty;
@Document
@TypeAlias("assetregisterbookform")

@ApiModel( value = "Assetregisterbookform", description = "assetregisterbookform" )
public class Assetregisterbookform  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
@JsonProperty("id")
	@Id 
 
 	private	String id;



	@ApiModelProperty( value = "created date", required = true )
@JsonProperty("created_date")
	@Field
 	private	String created_date;


	@ApiModelProperty( value = "updated date", required = true )
@JsonProperty("updated_date")
	@Field
 	private	String updated_date;



	@ApiModelProperty( value = "updated by value", required = true )
@JsonProperty("updated_by")
	@Field
 	private	long updated_by;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_status")
	@Field("new_status")
 	private	String new_status;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("floor_number")
	@Field("floor_number")
 	private	String floor_number;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("lock_code")
	@Field("lock_code")
 	private	String lock_code;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("project_name")
	@Field("project_name")
 	private	String project_name;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("type")
	@Field("type")
 	private	String type;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("supply")
	@Field("supply")
 	private	String supply;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("infra_own")
	@Field("infra_own")
 	private	String infra_own;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ol1_1")
	@Field("Ol1_1")
 	private	String ol1_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dact_on")
	@Field("dact_on")
 	private	String dact_on;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("sup_vendor")
	@Field("sup_vendor")
 	private	String sup_vendor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_location")
	@Field("new_location")
 	private	String new_location;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dram")
	@Field("dram")
 	private	String dram;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("isdn")
	@Field("ISDN")
 	private	String isdn;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_alternateid")
	@Field("new_alternateid")
 	private	String new_alternateid;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("wty_end_date")
	@Field("wty_end_date")
 	private	String wty_end_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("acc_no")
	@Field("acc_no")
 	private	String acc_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_expiry_date")
	@Field("ins_expiry_date")
 	private	String ins_expiry_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("census_reason")
	@Field("census_reason")
 	private	String census_reason;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("model")
	@Field("model")
 	private	String model;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("lvd")
	@Field("lvd")
 	private	String lvd;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("per")
	@Field("per")
 	private	String per;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("diswty_start_date")
	@Field("diswty_start_date")
 	private	String diswty_start_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_email")
	@Field("new_email")
 	private	String new_email;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dispinst_date")
	@Field("dispinst_date")
 	private	String dispinst_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("period")
	@Field("period")
 	private	String period;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("remk")
	@Field("remk")
 	private	String remk;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_joiningdate")
	@Field("new_joiningdate")
 	private	String new_joiningdate;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ip")
	@Field("IP")
 	private	String ip;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_entity")
	@Field("new_entity")
 	private	String new_entity;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("processor")
	@Field("processor")
 	private	String processor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ram_initial")
	@Field("RAM_initial")
 	private	String ram_initial;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_jobtype")
	@Field("new_jobtype")
 	private	String new_jobtype;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ar")
	@Field("ar")
 	private	String ar;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("usedus")
	@Field("usedus")
 	private	String usedus;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_designation")
	@Field("new_designation")
 	private	String new_designation;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_los")
	@Field("new_los")
 	private	String new_los;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inv_date")
	@Field("inv_date")
 	private	String inv_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inv_currency")
	@Field("inv_currency")
 	private	String inv_currency;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("carepack")
	@Field("carepack")
 	private	String carepack;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("doa")
	@Field("doa")
 	private	String doa;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("doc")
	@Field("doc")
 	private	String doc;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("created_by")
	@Field("Created_By")
 	private	String created_by;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("application1")
	@Field("application1")
 	private	String application1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("flash")
	@Field("flash")
 	private	String flash;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("status")
	@Field("status")
 	private	String status;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("end_date")
	@Field("end_date")
 	private	String end_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_policy_no")
	@Field("ins_policy_no")
 	private	String ins_policy_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("loc")
	@Field("loc")
 	private	String loc;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("hyper_1")
	@Field("hyper_1")
 	private	String hyper_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("hdd1")
	@Field("HDD1")
 	private	String hdd1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("scan")
	@Field("scan")
 	private	String scan;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("disppo_date")
	@Field("disppo_date")
 	private	String disppo_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("census_remarks")
	@Field("census_remarks")
 	private	String census_remarks;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("rack1")
	@Field("rack1")
 	private	String rack1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dact_type")
	@Field("dact_type")
 	private	String dact_type;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("sg")
	@Field("sg")
 	private	String sg;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("identity")
	@Field("identity")
 	private	String identity;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("erd")
	@Field("erd")
 	private	String erd;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("h_type")
	@Field("h_type")
 	private	String h_type;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("sl")
	@Field("sl")
 	private	String sl;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("amc_start_date")
	@Field("AMC_start_date")
 	private	String amc_start_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("currency")
	@Field("currency")
 	private	String currency;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("sp")
	@Field("sp")
 	private	String sp;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("start_date")
	@Field("start_date")
 	private	String start_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("approver")
	@Field("approver")
 	private	String approver;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_com_name")
	@Field("ins_com_name")
 	private	String ins_com_name;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("po_date")
	@Field("po_date")
 	private	String po_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("po_ref_no")
	@Field("po_ref_no")
 	private	String po_ref_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("file_no")
	@Field("file_no")
 	private	String file_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("amc_end_date")
	@Field("AMC_end_date")
 	private	String amc_end_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("diswty_end_date")
	@Field("diswty_end_date")
 	private	String diswty_end_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_gender")
	@Field("new_gender")
 	private	String new_gender;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dispins_expiry_date")
	@Field("dispins_expiry_date")
 	private	String dispins_expiry_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dat")
	@Field("DAT")
 	private	String dat;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ucode1")
	@Field("UCode1")
 	private	String ucode1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("hdd_initial")
	@Field("HDD_initial")
 	private	String hdd_initial;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("allocation_form_no")
	@Field("allocation_form_no")
 	private	String allocation_form_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("serial1")
	@Field("serial1")
 	private	String serial1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("esn")
	@Field("esn")
 	private	String esn;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("po_entity")
	@Field("po_entity")
 	private	String po_entity;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("wty_status")
	@Field("wty_status")
 	private	String wty_status;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("census_count")
	@Field("census_count")
 	private	String census_count;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ehdate")
	@Field("EhDate")
 	private	String ehdate;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("office")
	@Field("office")
 	private	String office;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("disinv_date")
	@Field("disinv_date")
 	private	String disinv_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("bill_entity")
	@Field("bill_entity")
 	private	String bill_entity;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("model_no")
	@Field("model_no")
 	private	String model_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_status")
	@Field("ins_status")
 	private	String ins_status;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("mode")
	@Field("mode")
 	private	String mode;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("acce_1")
	@Field("acce_1")
 	private	String acce_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dc1")
	@Field("DC1")
 	private	String dc1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("pin")
	@Field("pin")
 	private	String pin;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("doa1")
	@Field("doa1")
 	private	String doa1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("cpd")
	@Field("cpd")
 	private	String cpd;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("pstn")
	@Field("PSTN")
 	private	String pstn;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("mac_add")
	@Field("mac_add")
 	private	String mac_add;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inst_date")
	@Field("inst_date")
 	private	String inst_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("wty_terms")
	@Field("wty_terms")
 	private	String wty_terms;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("oprn_grp")
	@Field("oprn_grp")
 	private	String oprn_grp;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("srv_own")
	@Field("srv_own")
 	private	String srv_own;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("syssteward")
	@Field("SysSteward")
 	private	String syssteward;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("hyper")
	@Field("hyper")
 	private	String hyper;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("asset_number")
	@Field("asset_number")
 	private	String asset_number;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ddate")
	@Field("ddate")
 	private	String ddate;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("type2")
	@Field("type2")
 	private	String type2;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("created_on")
	@Field("Created_On")
 	private	String created_on;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("last")
	@Field("last")
 	private	String last;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dispdoa1")
	@Field("dispdoa1")
 	private	String dispdoa1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("payment_start_date")
	@Field("payment_start_date")
 	private	String payment_start_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("cpu")
	@Field("cpu")
 	private	String cpu;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("project_code")
	@Field("project_code")
 	private	String project_code;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_department")
	@Field("new_department")
 	private	String new_department;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("shelf")
	@Field("shelf")
 	private	String shelf;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ethernet")
	@Field("ethernet")
 	private	String ethernet;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("delivery_date")
	@Field("delivery_date")
 	private	String delivery_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dact_on_3")
	@Field("dact_on_3")
 	private	String dact_on_3;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("remarks_1")
	@Field("remarks_1")
 	private	String remarks_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dact_on_2")
	@Field("dact_on_2")
 	private	String dact_on_2;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inv_amt")
	@Field("inv_amt")
 	private	String inv_amt;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("dact_on_1")
	@Field("dact_on_1")
 	private	String dact_on_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("port")
	@Field("port")
 	private	String port;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_jobmode")
	@Field("new_jobmode")
 	private	String new_jobmode;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("seat_number")
	@Field("seat_number")
 	private	String seat_number;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inv_vendor")
	@Field("inv_vendor")
 	private	String inv_vendor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("eheditor")
	@Field("EhEditor")
 	private	String eheditor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("_class")
	@Field("_class")
 	private	String _class;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("engineer_1")
	@Field("engineer_1")
 	private	String engineer_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("fc")
	@Field("fc")
 	private	String fc;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("connection")
	@Field("connection")
 	private	String connection;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("inv_no")
	@Field("inv_no")
 	private	String inv_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("catrige_no")
	@Field("catrige_no")
 	private	String catrige_no;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("collected_from")
	@Field("collected_from")
 	private	String collected_from;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("srv_adm")
	@Field("srv_adm")
 	private	String srv_adm;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("code")
	@Field("code")
 	private	String code;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_subsbu")
	@Field("new_subsbu")
 	private	String new_subsbu;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("config")
	@Field("Config")
 	private	String config;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("loc5")
	@Field("loc5")
 	private	String loc5;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("airtelno")
	@Field("airtelno")
 	private	String airtelno;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("hdd")
	@Field("HDD")
 	private	String hdd;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("fr")
	@Field("fr")
 	private	String fr;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ol2_1")
	@Field("Ol2_1")
 	private	String ol2_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("speed")
	@Field("speed")
 	private	String speed;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("wty_start_date")
	@Field("wty_start_date")
 	private	String wty_start_date;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("disperd")
	@Field("disperd")
 	private	String disperd;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("printer_type")
	@Field("printer_type")
 	private	String printer_type;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ol2")
	@Field("Ol2")
 	private	String ol2;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ram1")
	@Field("RAM1")
 	private	String ram1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ol1")
	@Field("Ol1")
 	private	String ol1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("amc_terms")
	@Field("AMC_terms")
 	private	String amc_terms;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_orbitid")
	@Field("new_orbitid")
 	private	String new_orbitid;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("data_limit")
	@Field("Data_Limit")
 	private	String data_limit;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("make")
	@Field("make")
 	private	String make;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("lock_sl")
	@Field("lock_sl")
 	private	String lock_sl;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_jobfunction")
	@Field("new_jobfunction")
 	private	String new_jobfunction;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_name")
	@Field("new_name")
 	private	String new_name;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_renewal")
	@Field("ins_renewal")
 	private	String ins_renewal;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("rack")
	@Field("rack")
 	private	String rack;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("net_cat")
	@Field("net_cat")
 	private	String net_cat;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("cost")
	@Field("cost")
 	private	String cost;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ract_on_2")
	@Field("ract_on_2")
 	private	String ract_on_2;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("os")
	@Field("OS")
 	private	String os;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ract_on_1")
	@Field("ract_on_1")
 	private	String ract_on_1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ract_on_3")
	@Field("ract_on_3")
 	private	String ract_on_3;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("new_sbu")
	@Field("new_sbu")
 	private	String new_sbu;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("mobile")
	@Field("mobile")
 	private	String mobile;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ins_value")
	@Field("ins_value")
 	private	String ins_value;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("adaptor")
	@Field("adaptor")
 	private	String adaptor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("purpose")
	@Field("Purpose")
 	private	String purpose;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("location1")
	@Field("Location1")
 	private	String location1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("monitor")
	@Field("monitor")
 	private	String monitor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("po_year")
	@Field("po_year")
 	private	String po_year;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ip1")
	@Field("IP1")
 	private	String ip1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("date2")
	@Field("date2")
 	private	String date2;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ios")
	@Field("IOS")
 	private	String ios;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("date1")
	@Field("date1")
 	private	String date1;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("engineer")
	@Field("engineer")
 	private	String engineer;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("edor")
	@Field("edor")
 	private	String edor;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("room")
	@Field("room")
 	private	String room;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("rental")
	@Field("Rental")
 	private	String rental;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("application")
	@Field("application")
 	private	String application;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("serial")
	@Field("serial")
 	private	String serial;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("data_type")
	@Field("data_type")
 	private	String data_type;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("category")
	@Field("category")
 	private	String category;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("remarks")
	@Field("remarks")
 	private	String remarks;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("host_name")
	@Field("host_name")
 	private	String host_name;



	@ApiModelProperty( value = "Description", required = true )
@JsonProperty("ram")
	@Field("RAM")
 	private	String ram;




	public void setid(String id) {
		this.id = id;
	}


	public String getid() {
		return id;
	}

	public void setcreated_date(String created_date) {
		this.created_date = created_date;
	}


	public String getcreated_date() {
		return created_date;
	}

	public void setupdated_date(String updated_date) {
		this.updated_date = updated_date;
	}


	public String getupdated_date() {
		return updated_date;
	}

	public void setupdated_by(long updated_by) {
		this.updated_by = updated_by;
	}


	public long getupdated_by() {
		return updated_by;
	}

	public void setnew_status(String new_status) {
		this.new_status = new_status;
	}


	public String getnew_status() {
		return new_status;
	}

	public void setfloor_number(String floor_number) {
		this.floor_number = floor_number;
	}


	public String getfloor_number() {
		return floor_number;
	}

	public void setlock_code(String lock_code) {
		this.lock_code = lock_code;
	}


	public String getlock_code() {
		return lock_code;
	}

	public void setproject_name(String project_name) {
		this.project_name = project_name;
	}


	public String getproject_name() {
		return project_name;
	}

	public void settype(String type) {
		this.type = type;
	}


	public String gettype() {
		return type;
	}

	public void setsupply(String supply) {
		this.supply = supply;
	}


	public String getsupply() {
		return supply;
	}

	public void setinfra_own(String infra_own) {
		this.infra_own = infra_own;
	}


	public String getinfra_own() {
		return infra_own;
	}

	public void setol1_1(String ol1_1) {
		this.ol1_1 = ol1_1;
	}


	public String getol1_1() {
		return ol1_1;
	}

	public void setdact_on(String dact_on) {
		this.dact_on = dact_on;
	}


	public String getdact_on() {
		return dact_on;
	}

	public void setsup_vendor(String sup_vendor) {
		this.sup_vendor = sup_vendor;
	}


	public String getsup_vendor() {
		return sup_vendor;
	}

	public void setnew_location(String new_location) {
		this.new_location = new_location;
	}


	public String getnew_location() {
		return new_location;
	}

	public void setdram(String dram) {
		this.dram = dram;
	}


	public String getdram() {
		return dram;
	}

	public void setisdn(String isdn) {
		this.isdn = isdn;
	}


	public String getisdn() {
		return isdn;
	}

	public void setnew_alternateid(String new_alternateid) {
		this.new_alternateid = new_alternateid;
	}


	public String getnew_alternateid() {
		return new_alternateid;
	}

	public void setwty_end_date(String wty_end_date) {
		this.wty_end_date = wty_end_date;
	}


	public String getwty_end_date() {
		return wty_end_date;
	}

	public void setacc_no(String acc_no) {
		this.acc_no = acc_no;
	}


	public String getacc_no() {
		return acc_no;
	}

	public void setins_expiry_date(String ins_expiry_date) {
		this.ins_expiry_date = ins_expiry_date;
	}


	public String getins_expiry_date() {
		return ins_expiry_date;
	}

	public void setcensus_reason(String census_reason) {
		this.census_reason = census_reason;
	}


	public String getcensus_reason() {
		return census_reason;
	}

	public void setmodel(String model) {
		this.model = model;
	}


	public String getmodel() {
		return model;
	}

	public void setlvd(String lvd) {
		this.lvd = lvd;
	}


	public String getlvd() {
		return lvd;
	}

	public void setper(String per) {
		this.per = per;
	}


	public String getper() {
		return per;
	}

	public void setdiswty_start_date(String diswty_start_date) {
		this.diswty_start_date = diswty_start_date;
	}


	public String getdiswty_start_date() {
		return diswty_start_date;
	}

	public void setnew_email(String new_email) {
		this.new_email = new_email;
	}


	public String getnew_email() {
		return new_email;
	}

	public void setdispinst_date(String dispinst_date) {
		this.dispinst_date = dispinst_date;
	}


	public String getdispinst_date() {
		return dispinst_date;
	}

	public void setperiod(String period) {
		this.period = period;
	}


	public String getperiod() {
		return period;
	}

	public void setremk(String remk) {
		this.remk = remk;
	}


	public String getremk() {
		return remk;
	}

	
	public void setip(String ip) {
		this.ip = ip;
	}


	public String getip() {
		return ip;
	}

	public void setnew_entity(String new_entity) {
		this.new_entity = new_entity;
	}


	public String getnew_entity() {
		return new_entity;
	}

	public void setprocessor(String processor) {
		this.processor = processor;
	}


	public String getprocessor() {
		return processor;
	}

	public void setram_initial(String ram_initial) {
		this.ram_initial = ram_initial;
	}


	public String getram_initial() {
		return ram_initial;
	}

	public void setnew_jobtype(String new_jobtype) {
		this.new_jobtype = new_jobtype;
	}


	public String getnew_jobtype() {
		return new_jobtype;
	}

	public void setar(String ar) {
		this.ar = ar;
	}


	public String getar() {
		return ar;
	}

	public void setusedus(String usedus) {
		this.usedus = usedus;
	}


	public String getusedus() {
		return usedus;
	}

	public void setnew_designation(String new_designation) {
		this.new_designation = new_designation;
	}


	public String getnew_designation() {
		return new_designation;
	}

	public void setnew_los(String new_los) {
		this.new_los = new_los;
	}


	public String getnew_los() {
		return new_los;
	}

	public void setinv_date(String inv_date) {
		this.inv_date = inv_date;
	}


	public String getinv_date() {
		return inv_date;
	}

	public void setinv_currency(String inv_currency) {
		this.inv_currency = inv_currency;
	}


	public String getinv_currency() {
		return inv_currency;
	}

	public void setcarepack(String carepack) {
		this.carepack = carepack;
	}


	public String getcarepack() {
		return carepack;
	}

	public void setdoa(String doa) {
		this.doa = doa;
	}


	public String getdoa() {
		return doa;
	}

	public void setdoc(String doc) {
		this.doc = doc;
	}


	public String getdoc() {
		return doc;
	}

	public void setcreated_by(String created_by) {
		this.created_by = created_by;
	}


	public String getcreated_by() {
		return created_by;
	}

	public void setapplication1(String application1) {
		this.application1 = application1;
	}


	public String getapplication1() {
		return application1;
	}

	public void setflash(String flash) {
		this.flash = flash;
	}


	public String getflash() {
		return flash;
	}

	public void setstatus(String status) {
		this.status = status;
	}


	public String getstatus() {
		return status;
	}

	public void setend_date(String end_date) {
		this.end_date = end_date;
	}


	public String getend_date() {
		return end_date;
	}

	public void setins_policy_no(String ins_policy_no) {
		this.ins_policy_no = ins_policy_no;
	}


	public String getins_policy_no() {
		return ins_policy_no;
	}

	public void setloc(String loc) {
		this.loc = loc;
	}


	public String getloc() {
		return loc;
	}

	public void sethyper_1(String hyper_1) {
		this.hyper_1 = hyper_1;
	}


	public String gethyper_1() {
		return hyper_1;
	}

	public void sethdd1(String hdd1) {
		this.hdd1 = hdd1;
	}


	public String gethdd1() {
		return hdd1;
	}

	public void setscan(String scan) {
		this.scan = scan;
	}


	public String getscan() {
		return scan;
	}

	public void setdisppo_date(String disppo_date) {
		this.disppo_date = disppo_date;
	}


	public String getdisppo_date() {
		return disppo_date;
	}

	public void setcensus_remarks(String census_remarks) {
		this.census_remarks = census_remarks;
	}


	public String getcensus_remarks() {
		return census_remarks;
	}

	public void setrack1(String rack1) {
		this.rack1 = rack1;
	}


	public String getrack1() {
		return rack1;
	}

	public void setdact_type(String dact_type) {
		this.dact_type = dact_type;
	}


	public String getdact_type() {
		return dact_type;
	}

	public void setsg(String sg) {
		this.sg = sg;
	}


	public String getsg() {
		return sg;
	}

	public void setidentity(String identity) {
		this.identity = identity;
	}


	public String getidentity() {
		return identity;
	}

	public void seterd(String erd) {
		this.erd = erd;
	}


	public String geterd() {
		return erd;
	}

	public void seth_type(String h_type) {
		this.h_type = h_type;
	}


	public String geth_type() {
		return h_type;
	}

	public void setsl(String sl) {
		this.sl = sl;
	}


	public String getsl() {
		return sl;
	}

	public void setamc_start_date(String amc_start_date) {
		this.amc_start_date = amc_start_date;
	}


	public String getamc_start_date() {
		return amc_start_date;
	}

	public void setcurrency(String currency) {
		this.currency = currency;
	}


	public String getcurrency() {
		return currency;
	}

	public void setsp(String sp) {
		this.sp = sp;
	}


	public String getsp() {
		return sp;
	}

	public void setstart_date(String start_date) {
		this.start_date = start_date;
	}


	public String getstart_date() {
		return start_date;
	}

	public void setapprover(String approver) {
		this.approver = approver;
	}


	public String getapprover() {
		return approver;
	}

	public void setins_com_name(String ins_com_name) {
		this.ins_com_name = ins_com_name;
	}


	public String getins_com_name() {
		return ins_com_name;
	}

	public void setpo_date(String po_date) {
		this.po_date = po_date;
	}


	public String getpo_date() {
		return po_date;
	}

	public void setpo_ref_no(String po_ref_no) {
		this.po_ref_no = po_ref_no;
	}


	public String getpo_ref_no() {
		return po_ref_no;
	}

	
	//new_joiningdate
	
	public void setnew_joiningdate(String new_joiningdate) {
		this.new_joiningdate = new_joiningdate;
	}


	public String getnew_joiningdate() {
		return new_joiningdate;
	}
	
	public void setfile_no(String file_no) {
		this.file_no = file_no;
	}


	public String getfile_no() {
		return file_no;
	}

	public void setamc_end_date(String amc_end_date) {
		this.amc_end_date = amc_end_date;
	}


	public String getamc_end_date() {
		return amc_end_date;
	}

	public void setdiswty_end_date(String diswty_end_date) {
		this.diswty_end_date = diswty_end_date;
	}


	public String getdiswty_end_date() {
		return diswty_end_date;
	}

	public void setnew_gender(String new_gender) {
		this.new_gender = new_gender;
	}


	public String getnew_gender() {
		return new_gender;
	}

	public void setdispins_expiry_date(String dispins_expiry_date) {
		this.dispins_expiry_date = dispins_expiry_date;
	}


	public String getdispins_expiry_date() {
		return dispins_expiry_date;
	}

	public void setdat(String dat) {
		this.dat = dat;
	}


	public String getdat() {
		return dat;
	}

	public void setucode1(String ucode1) {
		this.ucode1 = ucode1;
	}


	public String getucode1() {
		return ucode1;
	}

	public void sethdd_initial(String hdd_initial) {
		this.hdd_initial = hdd_initial;
	}


	public String gethdd_initial() {
		return hdd_initial;
	}

	public void setallocation_form_no(String allocation_form_no) {
		this.allocation_form_no = allocation_form_no;
	}


	public String getallocation_form_no() {
		return allocation_form_no;
	}

	public void setserial1(String serial1) {
		this.serial1 = serial1;
	}


	public String getserial1() {
		return serial1;
	}

	public void setesn(String esn) {
		this.esn = esn;
	}


	public String getesn() {
		return esn;
	}

	public void setpo_entity(String po_entity) {
		this.po_entity = po_entity;
	}


	public String getpo_entity() {
		return po_entity;
	}

	public void setwty_status(String wty_status) {
		this.wty_status = wty_status;
	}


	public String getwty_status() {
		return wty_status;
	}

	public void setcensus_count(String census_count) {
		this.census_count = census_count;
	}


	public String getcensus_count() {
		return census_count;
	}

	public void setehdate(String ehdate) {
		this.ehdate = ehdate;
	}


	public String getehdate() {
		return ehdate;
	}

	public void setoffice(String office) {
		this.office = office;
	}


	public String getoffice() {
		return office;
	}

	public void setdisinv_date(String disinv_date) {
		this.disinv_date = disinv_date;
	}


	public String getdisinv_date() {
		return disinv_date;
	}

	public void setbill_entity(String bill_entity) {
		this.bill_entity = bill_entity;
	}


	public String getbill_entity() {
		return bill_entity;
	}

	public void setmodel_no(String model_no) {
		this.model_no = model_no;
	}


	public String getmodel_no() {
		return model_no;
	}

	public void setins_status(String ins_status) {
		this.ins_status = ins_status;
	}


	public String getins_status() {
		return ins_status;
	}

	public void setmode(String mode) {
		this.mode = mode;
	}


	public String getmode() {
		return mode;
	}

	public void setacce_1(String acce_1) {
		this.acce_1 = acce_1;
	}


	public String getacce_1() {
		return acce_1;
	}

	public void setdc1(String dc1) {
		this.dc1 = dc1;
	}


	public String getdc1() {
		return dc1;
	}

	public void setpin(String pin) {
		this.pin = pin;
	}


	public String getpin() {
		return pin;
	}

	public void setdoa1(String doa1) {
		this.doa1 = doa1;
	}


	public String getdoa1() {
		return doa1;
	}

	public void setcpd(String cpd) {
		this.cpd = cpd;
	}


	public String getcpd() {
		return cpd;
	}

	public void setpstn(String pstn) {
		this.pstn = pstn;
	}


	public String getpstn() {
		return pstn;
	}

	public void setmac_add(String mac_add) {
		this.mac_add = mac_add;
	}


	public String getmac_add() {
		return mac_add;
	}

	public void setinst_date(String inst_date) {
		this.inst_date = inst_date;
	}


	public String getinst_date() {
		return inst_date;
	}

	public void setwty_terms(String wty_terms) {
		this.wty_terms = wty_terms;
	}


	public String getwty_terms() {
		return wty_terms;
	}

	public void setoprn_grp(String oprn_grp) {
		this.oprn_grp = oprn_grp;
	}


	public String getoprn_grp() {
		return oprn_grp;
	}

	public void setsrv_own(String srv_own) {
		this.srv_own = srv_own;
	}


	public String getsrv_own() {
		return srv_own;
	}

	public void setsyssteward(String syssteward) {
		this.syssteward = syssteward;
	}


	public String getsyssteward() {
		return syssteward;
	}

	public void sethyper(String hyper) {
		this.hyper = hyper;
	}


	public String gethyper() {
		return hyper;
	}

	public void setasset_number(String asset_number) {
		this.asset_number = asset_number;
	}


	public String getasset_number() {
		return asset_number;
	}

	public void setddate(String ddate) {
		this.ddate = ddate;
	}


	public String getddate() {
		return ddate;
	}

	public void settype2(String type2) {
		this.type2 = type2;
	}


	public String gettype2() {
		return type2;
	}

	public void setcreated_on(String created_on) {
		this.created_on = created_on;
	}


	public String getcreated_on() {
		return created_on;
	}

	public void setlast(String last) {
		this.last = last;
	}


	public String getlast() {
		return last;
	}

	public void setdispdoa1(String dispdoa1) {
		this.dispdoa1 = dispdoa1;
	}


	public String getdispdoa1() {
		return dispdoa1;
	}

	public void setpayment_start_date(String payment_start_date) {
		this.payment_start_date = payment_start_date;
	}


	public String getpayment_start_date() {
		return payment_start_date;
	}

	public void setcpu(String cpu) {
		this.cpu = cpu;
	}


	public String getcpu() {
		return cpu;
	}

	public void setproject_code(String project_code) {
		this.project_code = project_code;
	}


	public String getproject_code() {
		return project_code;
	}

	public void setnew_department(String new_department) {
		this.new_department = new_department;
	}


	public String getnew_department() {
		return new_department;
	}

	public void setshelf(String shelf) {
		this.shelf = shelf;
	}


	public String getshelf() {
		return shelf;
	}

	public void setethernet(String ethernet) {
		this.ethernet = ethernet;
	}


	public String getethernet() {
		return ethernet;
	}

	public void setdelivery_date(String delivery_date) {
		this.delivery_date = delivery_date;
	}


	public String getdelivery_date() {
		return delivery_date;
	}

	public void setdact_on_3(String dact_on_3) {
		this.dact_on_3 = dact_on_3;
	}


	public String getdact_on_3() {
		return dact_on_3;
	}

	public void setremarks_1(String remarks_1) {
		this.remarks_1 = remarks_1;
	}


	public String getremarks_1() {
		return remarks_1;
	}

	public void setdact_on_2(String dact_on_2) {
		this.dact_on_2 = dact_on_2;
	}


	public String getdact_on_2() {
		return dact_on_2;
	}

	public void setinv_amt(String inv_amt) {
		this.inv_amt = inv_amt;
	}


	public String getinv_amt() {
		return inv_amt;
	}

	public void setdact_on_1(String dact_on_1) {
		this.dact_on_1 = dact_on_1;
	}


	public String getdact_on_1() {
		return dact_on_1;
	}

	public void setport(String port) {
		this.port = port;
	}


	public String getport() {
		return port;
	}

	public void setnew_jobmode(String new_jobmode) {
		this.new_jobmode = new_jobmode;
	}


	public String getnew_jobmode() {
		return new_jobmode;
	}

	public void setseat_number(String seat_number) {
		this.seat_number = seat_number;
	}


	public String getseat_number() {
		return seat_number;
	}

	public void setinv_vendor(String inv_vendor) {
		this.inv_vendor = inv_vendor;
	}


	public String getinv_vendor() {
		return inv_vendor;
	}

	public void seteheditor(String eheditor) {
		this.eheditor = eheditor;
	}


	public String geteheditor() {
		return eheditor;
	}

	public void set_class(String _class) {
		this._class = _class;
	}


	public String get_class() {
		return _class;
	}

	public void setengineer_1(String engineer_1) {
		this.engineer_1 = engineer_1;
	}


	public String getengineer_1() {
		return engineer_1;
	}

	public void setfc(String fc) {
		this.fc = fc;
	}


	public String getfc() {
		return fc;
	}

	public void setconnection(String connection) {
		this.connection = connection;
	}


	public String getconnection() {
		return connection;
	}

	public void setinv_no(String inv_no) {
		this.inv_no = inv_no;
	}


	public String getinv_no() {
		return inv_no;
	}

	public void setcatrige_no(String catrige_no) {
		this.catrige_no = catrige_no;
	}


	public String getcatrige_no() {
		return catrige_no;
	}

	public void setcollected_from(String collected_from) {
		this.collected_from = collected_from;
	}


	public String getcollected_from() {
		return collected_from;
	}

	public void setsrv_adm(String srv_adm) {
		this.srv_adm = srv_adm;
	}


	public String getsrv_adm() {
		return srv_adm;
	}

	public void setcode(String code) {
		this.code = code;
	}


	public String getcode() {
		return code;
	}

	public void setnew_subsbu(String new_subsbu) {
		this.new_subsbu = new_subsbu;
	}


	public String getnew_subsbu() {
		return new_subsbu;
	}

	public void setconfig(String config) {
		this.config = config;
	}


	public String getconfig() {
		return config;
	}

	public void setloc5(String loc5) {
		this.loc5 = loc5;
	}


	public String getloc5() {
		return loc5;
	}

	public void setairtelno(String airtelno) {
		this.airtelno = airtelno;
	}


	public String getairtelno() {
		return airtelno;
	}

	public void sethdd(String hdd) {
		this.hdd = hdd;
	}


	public String gethdd() {
		return hdd;
	}

	public void setfr(String fr) {
		this.fr = fr;
	}


	public String getfr() {
		return fr;
	}

	public void setol2_1(String ol2_1) {
		this.ol2_1 = ol2_1;
	}


	public String getol2_1() {
		return ol2_1;
	}

	public void setspeed(String speed) {
		this.speed = speed;
	}


	public String getspeed() {
		return speed;
	}

	public void setwty_start_date(String wty_start_date) {
		this.wty_start_date = wty_start_date;
	}


	public String getwty_start_date() {
		return wty_start_date;
	}

	public void setdisperd(String disperd) {
		this.disperd = disperd;
	}


	public String getdisperd() {
		return disperd;
	}

	public void setprinter_type(String printer_type) {
		this.printer_type = printer_type;
	}


	public String getprinter_type() {
		return printer_type;
	}

	public void setol2(String ol2) {
		this.ol2 = ol2;
	}


	public String getol2() {
		return ol2;
	}

	public void setram1(String ram1) {
		this.ram1 = ram1;
	}


	public String getram1() {
		return ram1;
	}

	public void setol1(String ol1) {
		this.ol1 = ol1;
	}


	public String getol1() {
		return ol1;
	}

	public void setamc_terms(String amc_terms) {
		this.amc_terms = amc_terms;
	}


	public String getamc_terms() {
		return amc_terms;
	}

	public void setnew_orbitid(String new_orbitid) {
		this.new_orbitid = new_orbitid;
	}


	public String getnew_orbitid() {
		return new_orbitid;
	}

	public void setdata_limit(String data_limit) {
		this.data_limit = data_limit;
	}


	public String getdata_limit() {
		return data_limit;
	}

	public void setmake(String make) {
		this.make = make;
	}


	public String getmake() {
		return make;
	}

	public void setlock_sl(String lock_sl) {
		this.lock_sl = lock_sl;
	}


	public String getlock_sl() {
		return lock_sl;
	}

	public void setnew_jobfunction(String new_jobfunction) {
		this.new_jobfunction = new_jobfunction;
	}


	public String getnew_jobfunction() {
		return new_jobfunction;
	}

	public void setnew_name(String new_name) {
		this.new_name = new_name;
	}


	public String getnew_name() {
		return new_name;
	}

	public void setins_renewal(String ins_renewal) {
		this.ins_renewal = ins_renewal;
	}


	public String getins_renewal() {
		return ins_renewal;
	}

	public void setrack(String rack) {
		this.rack = rack;
	}


	public String getrack() {
		return rack;
	}

	public void setnet_cat(String net_cat) {
		this.net_cat = net_cat;
	}


	public String getnet_cat() {
		return net_cat;
	}

	public void setcost(String cost) {
		this.cost = cost;
	}


	public String getcost() {
		return cost;
	}

	public void setract_on_2(String ract_on_2) {
		this.ract_on_2 = ract_on_2;
	}


	public String getract_on_2() {
		return ract_on_2;
	}

	public void setos(String os) {
		this.os = os;
	}


	public String getos() {
		return os;
	}

	public void setract_on_1(String ract_on_1) {
		this.ract_on_1 = ract_on_1;
	}


	public String getract_on_1() {
		return ract_on_1;
	}

	public void setract_on_3(String ract_on_3) {
		this.ract_on_3 = ract_on_3;
	}


	public String getract_on_3() {
		return ract_on_3;
	}

	public void setnew_sbu(String new_sbu) {
		this.new_sbu = new_sbu;
	}


	public String getnew_sbu() {
		return new_sbu;
	}

	public void setmobile(String mobile) {
		this.mobile = mobile;
	}


	public String getmobile() {
		return mobile;
	}

	public void setins_value(String ins_value) {
		this.ins_value = ins_value;
	}


	public String getins_value() {
		return ins_value;
	}

	public void setadaptor(String adaptor) {
		this.adaptor = adaptor;
	}


	public String getadaptor() {
		return adaptor;
	}

	public void setpurpose(String purpose) {
		this.purpose = purpose;
	}


	public String getpurpose() {
		return purpose;
	}

	public void setlocation1(String location1) {
		this.location1 = location1;
	}


	public String getlocation1() {
		return location1;
	}

	public void setmonitor(String monitor) {
		this.monitor = monitor;
	}


	public String getmonitor() {
		return monitor;
	}

	public void setpo_year(String po_year) {
		this.po_year = po_year;
	}


	public String getpo_year() {
		return po_year;
	}

	public void setip1(String ip1) {
		this.ip1 = ip1;
	}


	public String getip1() {
		return ip1;
	}

	public void setdate2(String date2) {
		this.date2 = date2;
	}


	public String getdate2() {
		return date2;
	}

	public void setios(String ios) {
		this.ios = ios;
	}


	public String getios() {
		return ios;
	}

	public void setdate1(String date1) {
		this.date1 = date1;
	}


	public String getdate1() {
		return date1;
	}

	public void setengineer(String engineer) {
		this.engineer = engineer;
	}


	public String getengineer() {
		return engineer;
	}

	public void setedor(String edor) {
		this.edor = edor;
	}


	public String getedor() {
		return edor;
	}

	public void setroom(String room) {
		this.room = room;
	}


	public String getroom() {
		return room;
	}

	public void setrental(String rental) {
		this.rental = rental;
	}


	public String getrental() {
		return rental;
	}

	public void setapplication(String application) {
		this.application = application;
	}


	public String getapplication() {
		return application;
	}

	public void setserial(String serial) {
		this.serial = serial;
	}


	public String getserial() {
		return serial;
	}

	public void setdata_type(String data_type) {
		this.data_type = data_type;
	}


	public String getdata_type() {
		return data_type;
	}

	public void setcategory(String category) {
		this.category = category;
	}


	public String getcategory() {
		return category;
	}

	public void setremarks(String remarks) {
		this.remarks = remarks;
	}


	public String getremarks() {
		return remarks;
	}

	public void sethost_name(String host_name) {
		this.host_name = host_name;
	}


	public String gethost_name() {
		return host_name;
	}

	public void setram(String ram) {
		this.ram = ram;
	}


	public String getram() {
		return ram;
	}




}