package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Accessories;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("AccessoriesDao")
public class AccessoriesDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(AccessoriesDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Accessories noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Accessories object will return
	*@throws Exception
	*/

	public Accessories accessories_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("accessories_search_for_update Dao started operation!");

		   Accessories  the_accessories = couchbaseTemplate.findById(id,Accessories.class);
		  return the_accessories;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Accessories noun from  database
	*
	*
	*@return List of Accessories object will return
	*@throws Exception
	*/

	public ArrayList<Accessories> get_all_accessories() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_accessories Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Accessories>)  couchbaseTemplate.findByView("dev_accessories","accessories_by_name",query,Accessories.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Accessories noun into database
	*@param Accessories
	*@param user
	*@return Accessories object will return
	*@throws Exception
	*/


	public Accessories create_accessories(Accessories Accessories ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_accessories Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Accessories.setId(clientKey);
 		 couchbaseTemplate.save(Accessories);
 		 String viewName = "accessories_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Accessories\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_accessories");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Accessories;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Accessories noun into database
	*@param Accessories
	*@param user
	*@return the_Accessories object will return
	*@throws Exception
	*/


	public Accessories update_accessories(Accessories Accessories) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_accessories Dao started operation!");

 		 couchbaseTemplate.save(Accessories);
		  return Accessories;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Accessories noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Accessories id deleted based on id
	*@throws Exception
	*/


	public String  delete_accessories(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_accessories Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}