package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.AllocatedFrom;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("AllocatedFromDao")
public class AllocatedFromDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(AllocatedFromDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  AllocatedFrom noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AllocatedFrom object will return
	*@throws Exception
	*/

	public AllocatedFrom allocatedfrom_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("allocatedfrom_search_for_update Dao started operation!");

		   AllocatedFrom  the_allocatedfrom = couchbaseTemplate.findById(id,AllocatedFrom.class);
		  return the_allocatedfrom;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  AllocatedFrom noun from  database
	*
	*
	*@return List of AllocatedFrom object will return
	*@throws Exception
	*/

	public ArrayList<AllocatedFrom> get_all_allocatedfrom() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_allocatedfrom Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<AllocatedFrom>)  couchbaseTemplate.findByView("dev_allocatedfrom","allocatedfrom_by_name",query,AllocatedFrom.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  AllocatedFrom noun into database
	*@param AllocatedFrom
	*@param user
	*@return AllocatedFrom object will return
	*@throws Exception
	*/


	public AllocatedFrom create_allocatedfrom(AllocatedFrom AllocatedFrom ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_allocatedfrom Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 AllocatedFrom.setId(clientKey);
 		 couchbaseTemplate.save(AllocatedFrom);
 		 String viewName = "allocatedfrom_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.AllocatedFrom\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_allocatedfrom");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return AllocatedFrom;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  AllocatedFrom noun into database
	*@param AllocatedFrom
	*@param user
	*@return the_AllocatedFrom object will return
	*@throws Exception
	*/


	public AllocatedFrom update_allocatedfrom(AllocatedFrom AllocatedFrom) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_allocatedfrom Dao started operation!");

 		 couchbaseTemplate.save(AllocatedFrom);
		  return AllocatedFrom;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  AllocatedFrom noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AllocatedFrom id deleted based on id
	*@throws Exception
	*/


	public String  delete_allocatedfrom(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_allocatedfrom Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}