package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Application;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("Application_ActivityDao")
public class Application_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Application_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Application noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Application object will return
	*@throws Exception
	*/

	public Application application_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("application_search_for_update Dao started operation!");

		   Application  the_application = couchbaseTemplate.findById(id,Application.class);
		  return the_application;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Application noun from  database
	*
	*
	*@return List of Application object will return
	*@throws Exception
	*/

	public ArrayList<Application> get_all_application() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_application Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Application>)  couchbaseTemplate.findByView("dev_application","application_by_name",query,Application.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Application noun into database
	*@param Application
	*@param user
	*@return Application object will return
	*@throws Exception
	*/


	public Application create_application(Application Application ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_application Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Application.setId(clientKey);
 		 couchbaseTemplate.save(Application);
 		 String viewName = "application_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Application\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_application");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Application;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Application noun into database
	*@param Application
	*@param user
	*@return the_Application object will return
	*@throws Exception
	*/


	public Application update_application(Application Application) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_application Dao started operation!");

 		 couchbaseTemplate.save(Application);
		  return Application;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Application noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Application id deleted based on id
	*@throws Exception
	*/


	public String  delete_application(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_application Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}