package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.ApproverOrProjectManager;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("ApproverOrProjectManagerDao")
public class ApproverOrProjectManagerDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(ApproverOrProjectManagerDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  ApproverOrProjectManager noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ApproverOrProjectManager object will return
	*@throws Exception
	*/

	public ApproverOrProjectManager approverorprojectmanager_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("approverorprojectmanager_search_for_update Dao started operation!");

		   ApproverOrProjectManager  the_approverorprojectmanager = couchbaseTemplate.findById(id,ApproverOrProjectManager.class);
		  return the_approverorprojectmanager;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  ApproverOrProjectManager noun from  database
	*
	*
	*@return List of ApproverOrProjectManager object will return
	*@throws Exception
	*/

	public ArrayList<ApproverOrProjectManager> get_all_approverorprojectmanager() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_approverorprojectmanager Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<ApproverOrProjectManager>)  couchbaseTemplate.findByView("dev_approverorprojectmanager","approverorprojectmanager_by_name",query,ApproverOrProjectManager.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  ApproverOrProjectManager noun into database
	*@param ApproverOrProjectManager
	*@param user
	*@return ApproverOrProjectManager object will return
	*@throws Exception
	*/


	public ApproverOrProjectManager create_approverorprojectmanager(ApproverOrProjectManager ApproverOrProjectManager ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_approverorprojectmanager Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 ApproverOrProjectManager.setId(clientKey);
 		 couchbaseTemplate.save(ApproverOrProjectManager);
 		 String viewName = "approverorprojectmanager_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.ApproverOrProjectManager\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_approverorprojectmanager");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return ApproverOrProjectManager;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  ApproverOrProjectManager noun into database
	*@param ApproverOrProjectManager
	*@param user
	*@return the_ApproverOrProjectManager object will return
	*@throws Exception
	*/


	public ApproverOrProjectManager update_approverorprojectmanager(ApproverOrProjectManager ApproverOrProjectManager) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_approverorprojectmanager Dao started operation!");

 		 couchbaseTemplate.save(ApproverOrProjectManager);
		  return ApproverOrProjectManager;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  ApproverOrProjectManager noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ApproverOrProjectManager id deleted based on id
	*@throws Exception
	*/


	public String  delete_approverorprojectmanager(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_approverorprojectmanager Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}