package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.BillingEntity;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("BillingEntity_ActivityDao")
public class BillingEntity_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(BillingEntity_ActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  BillingEntity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_BillingEntity object will return
	*@throws Exception
	*/

	public BillingEntity billingentity_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("billingentity_search_for_update Dao started operation!");

		   BillingEntity  the_billingentity = couchbaseTemplate.findById(id,BillingEntity.class);
		  return the_billingentity;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  BillingEntity noun from  database
	*
	*
	*@return List of BillingEntity object will return
	*@throws Exception
	*/

	public ArrayList<BillingEntity> get_all_billingentity() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_billingentity Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<BillingEntity>)  couchbaseTemplate.findByView("dev_billingentity","billingentity_by_name",query,BillingEntity.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  BillingEntity noun into database
	*@param BillingEntity
	*@param user
	*@return BillingEntity object will return
	*@throws Exception
	*/


	public BillingEntity create_billingentity(BillingEntity BillingEntity ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_billingentity Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 BillingEntity.setId(clientKey);
 		 couchbaseTemplate.save(BillingEntity);
 		 String viewName = "billingentity_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.BillingEntity\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_billingentity");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return BillingEntity;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  BillingEntity noun into database
	*@param BillingEntity
	*@param user
	*@return the_BillingEntity object will return
	*@throws Exception
	*/


	public BillingEntity update_billingentity(BillingEntity BillingEntity) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_billingentity Dao started operation!");

 		 couchbaseTemplate.save(BillingEntity);
		  return BillingEntity;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  BillingEntity noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_BillingEntity id deleted based on id
	*@throws Exception
	*/


	public String  delete_billingentity(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_billingentity Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}