package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.DataTransferLimit;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("DataTransferLimitDao")
public class DataTransferLimitDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(DataTransferLimitDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  DataTransferLimit noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_DataTransferLimit object will return
	*@throws Exception
	*/

	public DataTransferLimit datatransferlimit_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("datatransferlimit_search_for_update Dao started operation!");

		   DataTransferLimit  the_datatransferlimit = couchbaseTemplate.findById(id,DataTransferLimit.class);
		  return the_datatransferlimit;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  DataTransferLimit noun from  database
	*
	*
	*@return List of DataTransferLimit object will return
	*@throws Exception
	*/

	public ArrayList<DataTransferLimit> get_all_datatransferlimit() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_datatransferlimit Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<DataTransferLimit>)  couchbaseTemplate.findByView("dev_datatransferlimit","datatransferlimit_by_name",query,DataTransferLimit.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  DataTransferLimit noun into database
	*@param DataTransferLimit
	*@param user
	*@return DataTransferLimit object will return
	*@throws Exception
	*/


	public DataTransferLimit create_datatransferlimit(DataTransferLimit DataTransferLimit ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_datatransferlimit Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 DataTransferLimit.setId(clientKey);
 		 couchbaseTemplate.save(DataTransferLimit);
 		 String viewName = "datatransferlimit_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.DataTransferLimit\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_datatransferlimit");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return DataTransferLimit;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  DataTransferLimit noun into database
	*@param DataTransferLimit
	*@param user
	*@return the_DataTransferLimit object will return
	*@throws Exception
	*/


	public DataTransferLimit update_datatransferlimit(DataTransferLimit DataTransferLimit) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_datatransferlimit Dao started operation!");

 		 couchbaseTemplate.save(DataTransferLimit);
		  return DataTransferLimit;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  DataTransferLimit noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_DataTransferLimit id deleted based on id
	*@throws Exception
	*/


	public String  delete_datatransferlimit(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_datatransferlimit Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}