package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.Engineer;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("EngineerDao")
public class EngineerDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(EngineerDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Engineer noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Engineer object will return
	*@throws Exception
	*/

	public Engineer engineer_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("engineer_search_for_update Dao started operation!");

		   Engineer  the_engineer = couchbaseTemplate.findById(id,Engineer.class);
		  return the_engineer;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Engineer noun from  database
	*
	*
	*@return List of Engineer object will return
	*@throws Exception
	*/

	public ArrayList<Engineer> get_all_engineer() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_engineer Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<Engineer>)  couchbaseTemplate.findByView("dev_engineer","engineer_by_name",query,Engineer.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Engineer noun into database
	*@param Engineer
	*@param user
	*@return Engineer object will return
	*@throws Exception
	*/


	public Engineer create_engineer(Engineer Engineer ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_engineer Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 Engineer.setId(clientKey);
 		 couchbaseTemplate.save(Engineer);
 		 String viewName = "engineer_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.Engineer\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_engineer");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return Engineer;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Engineer noun into database
	*@param Engineer
	*@param user
	*@return the_Engineer object will return
	*@throws Exception
	*/


	public Engineer update_engineer(Engineer Engineer) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_engineer Dao started operation!");

 		 couchbaseTemplate.save(Engineer);
		  return Engineer;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Engineer noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Engineer id deleted based on id
	*@throws Exception
	*/


	public String  delete_engineer(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_engineer Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}