package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.LNID;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("LNIDDao")
public class LNIDDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(LNIDDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  LNID noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_LNID object will return
	*@throws Exception
	*/

	public LNID lnid_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("lnid_search_for_update Dao started operation!");

		   LNID  the_lnid = couchbaseTemplate.findById(id,LNID.class);
		  return the_lnid;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  LNID noun from  database
	*
	*
	*@return List of LNID object will return
	*@throws Exception
	*/

	public ArrayList<LNID> get_all_lnid() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_lnid Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<LNID>)  couchbaseTemplate.findByView("dev_lnid","lnid_by_name",query,LNID.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  LNID noun into database
	*@param LNID
	*@param user
	*@return LNID object will return
	*@throws Exception
	*/


	public LNID create_lnid(LNID LNID ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_lnid Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 LNID.setId(clientKey);
 		 couchbaseTemplate.save(LNID);
 		 String viewName = "lnid_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.LNID\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_lnid");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return LNID;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  LNID noun into database
	*@param LNID
	*@param user
	*@return the_LNID object will return
	*@throws Exception
	*/


	public LNID update_lnid(LNID LNID) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_lnid Dao started operation!");

 		 couchbaseTemplate.save(LNID);
		  return LNID;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  LNID noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_LNID id deleted based on id
	*@throws Exception
	*/


	public String  delete_lnid(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_lnid Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}