package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.ModeOfUse;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("ModeOfUseDao")
public class ModeOfUseDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(ModeOfUseDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  ModeOfUse noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ModeOfUse object will return
	*@throws Exception
	*/

	public ModeOfUse modeofuse_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("modeofuse_search_for_update Dao started operation!");

		   ModeOfUse  the_modeofuse = couchbaseTemplate.findById(id,ModeOfUse.class);
		  return the_modeofuse;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  ModeOfUse noun from  database
	*
	*
	*@return List of ModeOfUse object will return
	*@throws Exception
	*/

	public ArrayList<ModeOfUse> get_all_modeofuse() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_modeofuse Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<ModeOfUse>)  couchbaseTemplate.findByView("dev_modeofuse","modeofuse_by_name",query,ModeOfUse.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  ModeOfUse noun into database
	*@param ModeOfUse
	*@param user
	*@return ModeOfUse object will return
	*@throws Exception
	*/


	public ModeOfUse create_modeofuse(ModeOfUse ModeOfUse ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_modeofuse Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 ModeOfUse.setId(clientKey);
 		 couchbaseTemplate.save(ModeOfUse);
 		 String viewName = "modeofuse_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.ModeOfUse\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_modeofuse");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return ModeOfUse;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  ModeOfUse noun into database
	*@param ModeOfUse
	*@param user
	*@return the_ModeOfUse object will return
	*@throws Exception
	*/


	public ModeOfUse update_modeofuse(ModeOfUse ModeOfUse) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_modeofuse Dao started operation!");

 		 couchbaseTemplate.save(ModeOfUse);
		  return ModeOfUse;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  ModeOfUse noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ModeOfUse id deleted based on id
	*@throws Exception
	*/


	public String  delete_modeofuse(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_modeofuse Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}