package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.ProjectName;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("ProjectNameActivityDao")
public class ProjectNameActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(ProjectNameActivityDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  ProjectName noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ProjectName object will return
	*@throws Exception
	*/

	public ProjectName projectname_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("projectname_search_for_update Dao started operation!");

		   ProjectName  the_projectname = couchbaseTemplate.findById(id,ProjectName.class);
		  return the_projectname;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  ProjectName noun from  database
	*
	*
	*@return List of ProjectName object will return
	*@throws Exception
	*/

	public ArrayList<ProjectName> get_all_projectname() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_projectname Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<ProjectName>)  couchbaseTemplate.findByView("dev_projectname","projectname_by_name",query,ProjectName.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  ProjectName noun into database
	*@param ProjectName
	*@param user
	*@return ProjectName object will return
	*@throws Exception
	*/


	public ProjectName create_projectname(ProjectName ProjectName ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_projectname Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 ProjectName.setId(clientKey);
 		 couchbaseTemplate.save(ProjectName);
 		 String viewName = "projectname_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.ProjectName\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_projectname");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return ProjectName;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  ProjectName noun into database
	*@param ProjectName
	*@param user
	*@return the_ProjectName object will return
	*@throws Exception
	*/


	public ProjectName update_projectname(ProjectName ProjectName) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_projectname Dao started operation!");

 		 couchbaseTemplate.save(ProjectName);
		  return ProjectName;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  ProjectName noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ProjectName id deleted based on id
	*@throws Exception
	*/


	public String  delete_projectname(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_projectname Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}