package com.AssetRegisterBook.dao.couchbase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.log4j.*;

import com.couchbase.client.CouchbaseClient;
import com.couchbase.client.protocol.views.DesignDocument;
import com.couchbase.client.protocol.views.Query;
import com.couchbase.client.protocol.views.Stale;

import org.springframework.data.couchbase.core.CouchbaseTemplate;
import com.couchbase.client.protocol.views.ViewDesign;


import com.AssetRegisterBook.domain.core.ReasonForNotCount;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Repository("ReasonForNotCountDao")
public class ReasonForNotCountDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(ReasonForNotCountDao.class.getName());

	@Autowired
 	CouchbaseTemplate couchbaseTemplate;

 	@Autowired
 	CouchbaseClient client ;


	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  ReasonForNotCount noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ReasonForNotCount object will return
	*@throws Exception
	*/

	public ReasonForNotCount reasonfornotcount_search_for_update(String id) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("reasonfornotcount_search_for_update Dao started operation!");

		   ReasonForNotCount  the_reasonfornotcount = couchbaseTemplate.findById(id,ReasonForNotCount.class);
		  return the_reasonfornotcount;

	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  ReasonForNotCount noun from  database
	*
	*
	*@return List of ReasonForNotCount object will return
	*@throws Exception
	*/

	public ArrayList<ReasonForNotCount> get_all_reasonfornotcount() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_reasonfornotcount Dao started operation!");


		   Query query = new Query();
		   query.setIncludeDocs(true);
		   query.setStale( Stale.FALSE );

		  return (ArrayList<ReasonForNotCount>)  couchbaseTemplate.findByView("dev_reasonfornotcount","reasonfornotcount_by_name",query,ReasonForNotCount.class);

	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  ReasonForNotCount noun into database
	*@param ReasonForNotCount
	*@param user
	*@return ReasonForNotCount object will return
	*@throws Exception
	*/


	public ReasonForNotCount create_reasonfornotcount(ReasonForNotCount ReasonForNotCount ) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_reasonfornotcount Dao started operation!");

 		 String key = "Document_count";
 		 String  clientKey =  Long.toString(client.incr(key,1,1));
 		 ReasonForNotCount.setId(clientKey);
 		 couchbaseTemplate.save(ReasonForNotCount);
 		 String viewName = "reasonfornotcount_by_name";
 		  String mapFunction =  "function (doc, meta) {"
 		 +  "if (doc._class == \"com.AssetRegisterBook.domain.core.ReasonForNotCount\") {"
 		  + "emit(null, null);"
 		  +" }"
 		 +"}";
 		 DesignDocument designDoc = new DesignDocument("dev_reasonfornotcount");
 		 System.err.println("-- > designDoc - > "+designDoc.getName()+"-> lan - > "+designDoc.getLanguage());
 		 ViewDesign view = new ViewDesign(viewName, mapFunction);
 		 System.err.println("-- > view - > "+view.getName()+"-> lan - > "+view.getReduce().toString());
 		 designDoc.getViews().add(view);
 		 client.createDesignDoc(designDoc);

		  return ReasonForNotCount;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  ReasonForNotCount noun into database
	*@param ReasonForNotCount
	*@param user
	*@return the_ReasonForNotCount object will return
	*@throws Exception
	*/


	public ReasonForNotCount update_reasonfornotcount(ReasonForNotCount ReasonForNotCount) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_reasonfornotcount Dao started operation!");

 		 couchbaseTemplate.save(ReasonForNotCount);
		  return ReasonForNotCount;

	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  ReasonForNotCount noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_ReasonForNotCount id deleted based on id
	*@throws Exception
	*/


	public String  delete_reasonfornotcount(String  id) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_reasonfornotcount Dao started operation!");

 		 client.delete(id);
		  return "{\"status\":\"success\"}";

	}



}