server:
  port: 8080

security:
  basic:
    enabled: false

entitymanager:
  packagesToScan: com.AssetRegisterBook.*

#34.205.61.224

#10.243.76.68 PWC

couchbase:
  cluster:
    ip: 10.243.76.68
    bucket: ARB
    username: gepuser
    password: tang3456
    db:
      password: 


 
